### PR TITLE
fix(kit): remove pure getNativeElements

### LINKED ISSUE #7017: 🐞 - Stepper: autoscroll to selected element not working after updating stepper state
### Playground Link

https://stackblitz.com/edit/angular-fasgvr?file=src%2Fapp%2Fapp.component.html

### Description

https://github.com/taiga-family/taiga-ui/assets/1676900/7d41e751-b7fa-41fa-8792-da71f935cb0e

In the example it looks at steps$ observable, and the autoscroll works perfectly, both when switching the stepper itself and when navigating through pages. But as soon as I update the steps$ value (in my example it happens after buttons click), the autoscroll doesn't move anymore.

### Angular version

12.2

### Taiga UI version

3.70.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by AlexeyPortnyagin**
Closes #7017

### CODE REVIEW

File: projects/kit/components/stepper/stepper.component.ts [hunk 1]
```diff
@@ -71,9 +70,9 @@ export class TuiStepperComponent {
     }
 
     public indexOf(step: HTMLElement): number {
-        return tuiGetOriginalArrayFromQueryList(this.steps).findIndex(
```
Comment (AlexeyPortnyagin) [inline projects/kit/components/stepper/stepper.component.ts:74]: It looked like it could be replaced, correct if wrong

Comment (waterplea) [reply projects/kit/components/stepper/stepper.component.ts:74]: It is used by `StepComponent` to determine if it is the active one and to activate it. `toArray` creates a new array which is a bit slower than `tuiGetOriginalArrayFromQueryList`. We can get rid of `indexOf` in favor of 
```ts
isActive(step: HTMLElement): boolean {
  return this.steps.get(this.activeItemIndex)?.nativeElement === step;
}
```
and we also need to change `activate` method to accept `HTMLElement` instead of index then.

Comment (AlexeyPortnyagin) [reply projects/kit/components/stepper/stepper.component.ts:74]: Changing `activate` method looks like a breaking change. This is a public method, perhaps someone uses it in their projects. Is this really necessary? Maybe just return `tuiGetOriginalArrayFromQueryList`

Comment (waterplea) [reply projects/kit/components/stepper/stepper.component.ts:74]: Sure, let's just return it.

**Review by waterplea — APPROVED** [review]

**Comment by waterplea** [comment]
Same thing will be needed for v3.x branch

**Comment by AlexeyPortnyagin** [comment]
> Same thing will be needed for v3.x branch

Can you tell me how to pull up the 3.x branch in my fork?

**Review by vladimirpotekhin — APPROVED** [review]

**Review by splincode — APPROVED** [review]
