### PR TITLE
fix(core): close `Hint` and `Dropdown` when host is detached from dom

### LINKED ISSUE #7531: 🐞 - Дропдауны и тултипы не скрываются, если хост пропал из дома
### Playground Link

https://stackblitz.com/edit/angular-e8yupy?file=src%2Fapp%2Fapp.component.html

### Description

У нас при переходе на другую страницу в приложении, из дома пропадают компоненты (но ngOnDestroy не происходит), в таком случае дропдауны и тултипы продолжают существовать, смещаясь в левый верхний угол. нужно чтобы они скрывались, если хоста нет в доме

### Angular version

15.x.x

### Taiga UI version

3.74.x

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
cherry-pick + component test

Closes #7531

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/core/directives/dropdown/dropdown.component.ts [hunk 1]
```diff
@@ -67,7 +67,11 @@ export class TuiDropdownComponent implements OnInit {
             takeUntilDestroyed(),
         )
         .subscribe(([top, left]) => {
-            this.update(top, left);
+            if (this.directive.el.isConnected) {
+                this.update(top, left);
+            } else {
+                this.directive.toggle(false);
+            }
```
Comment (splincode) [inline projects/core/directives/dropdown/dropdown.component.ts:74]: Is this how it should be?

image

**Review by waterplea — APPROVED** [review]

File: projects/core/directives/dropdown/dropdown.component.ts (hunk 1 above)
Comment (vladimirpotekhin) [reply projects/core/directives/dropdown/dropdown.component.ts:74]: Yes, approach from the screenshot is intended for hints, because the hints don't close immediately, but with a delay. The dropdown does not have this problem
