### PR TITLE
chore: fix `InputCard` after borders were removed

### LINKED ISSUE #9131: 🐞 - old docs search input keybinding
### Code Example URL

stackblitz.com

### Description

If you disable the new Algolia search and re-enable the old one, the old search keybinding (`/`) will not work anymore.

Broken in #9081

### Taiga UI version

4.7.0

### Browser Used

Chrome

### OS Used

Windows

### PR DESCRIPTION
**Pull request by waterplea**
Close #9131

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/addon-commerce/components/input-card/input-card.component.ts [hunk 1]
```diff
@@ -1,40 +1,72 @@
...
         '[autocomplete]': 'autocomplete ? "cc-number" : "off"',
-        '[style.background-image]': 'backgroundImage',
     },
 })
 export class TuiInputCard implements OnInit {
     private readonly icons = inject(TUI_PAYMENT_SYSTEM_ICONS);
     private readonly options = inject(TUI_INPUT_CARD_OPTIONS);
     private readonly resolver = tuiInjectIconResolver();
     private readonly control = inject(NgControl);
+    private readonly value = toSignal(
```
Comment (vladimirpotekhin) [inline projects/addon-commerce/components/input-card/input-card.component.ts:52]: сhecking requirement for resolving comments

**Review by vladimirpotekhin — APPROVED** [review]

File: projects/addon-doc/components/navigation/navigation.component.ts [hunk 2]
```diff
@@ -169,9 +170,9 @@ export class TuiDocNavigation {
     protected onFocusSearch(event: KeyboardEvent): void {
         if (
             event.code === 'Slash' &&
```
Comment (hakimio) [inline projects/addon-doc/components/navigation/navigation.component.ts:172]: `(window:keydown)` could be changed to `(window:keydown./)` to avoid checking for key code here.

Comment (waterplea) [reply projects/addon-doc/components/navigation/navigation.component.ts:172]: Yes, I tried that initially, but it wouldn't work for other languages
