### PR TITLE
fix(core): fix overriding default dropdown options

### LINKED ISSUE #4935: 🐞 - TuiComboBox incorrectly gets width parameter
### Playground Link

https://stackblitz.com/edit/angular-eiecws-1krhgo?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.less

### Description

If u set tuiDropdownLimitWidth="auto" instead of [tuiDropdownLimitWidth]="'auto'" - combobox ignore it. It's working only without additional inner <input / parameter passed throught ng-content. 

### Angular version

12.2.17

### Taiga UI version

latest (3)

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
Fixes #4935

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/core/components/textfield/textfield.component.ts [hunk 1]
```diff
@@ -83,6 +82,9 @@ export class TuiTextfieldComponent<T> implements TuiDataListHost<T> {
     protected readonly control?: NgControl;
 
     protected readonly icons = inject(TUI_COMMON_ICONS);
+    protected readonly override = tuiOverrideDefaultOptions(TUI_DROPDOWN_OPTIONS, {
```
Comment (splincode) [inline projects/core/components/textfield/textfield.component.ts:85]: image

**Review by waterplea — APPROVED** [review]
