### PR TITLE
fix(core): `Textfield` ensure non-erasable affixes actually deleted

### LINKED ISSUE #11634: 🐞 - behavior between chrome and safari is different when press cleaner in InputPhoneInternational
### Reproduction url

https://taiga-ui.dev/components/input-phone-international/API?tuiTextfieldCleaner=true

### Description

Press cleaner

Image

the behavior between chrome and safari is different

### Taiga UI version

latest

### Browser Used

Safari

### OS Used

macOS

### PR DESCRIPTION
**Pull request by splincode**
Fixes #11634

### CODE REVIEW

File: projects/addon-commerce/components/input-card-group/input-card-group.component.ts [hunk 1]
```diff
@@ -292,6 +292,15 @@ export class TuiInputCardGroup
             e?.nativeElement.focus();
             e?.nativeElement.select();
             e?.nativeElement.ownerDocument.execCommand('delete');
+
+            /**
+             * @note:
```
Comment (nsbarsukov) [inline projects/addon-commerce/components/input-card-group/input-card-group.component.ts]: Do we really need `@note` ?

File: projects/addon-commerce/components/input-card-group/input-card-group.component.ts [hunk 2]
```diff
@@ -292,6 +292,15 @@ export class TuiInputCardGroup
...
+             * ensure non-erasable prefix actually deleted
```
Comment (nsbarsukov) [inline projects/addon-commerce/components/input-card-group/input-card-group.component.ts]: Let's use word `affixes` because it is also relevant for postfix too

```suggestion
             * ensure non-erasable affixes actually deleted
```

**Review by nsbarsukov — APPROVED** [review]

File: projects/addon-commerce/components/input-card-group/input-card-group.component.ts [hunk 3]
```diff
@@ -292,6 +292,12 @@ export class TuiInputCardGroup
             e?.nativeElement.focus();
             e?.nativeElement.select();
             e?.nativeElement.ownerDocument.execCommand('delete');
+
+            if (e?.nativeElement) {
```
Comment (waterplea) [inline projects/addon-commerce/components/input-card-group/input-card-group.component.ts]: This component does not have any affixes, it's irrelevant here

**Review by waterplea — APPROVED** [review]

File: projects/addon-commerce/components/input-card-group/input-card-group.component.ts (hunk 3 above)
Comment (splincode) [reply projects/addon-commerce/components/input-card-group/input-card-group.component.ts]: fixed

File: projects/addon-commerce/components/input-card-group/input-card-group.component.ts (hunk 1 above)
Comment (splincode) [reply projects/addon-commerce/components/input-card-group/input-card-group.component.ts]: fixed

File: projects/addon-commerce/components/input-card-group/input-card-group.component.ts (hunk 2 above)
Comment (splincode) [reply projects/addon-commerce/components/input-card-group/input-card-group.component.ts]: fixed
