### PR TITLE
fix(kit): `DataListWrapper` fails to emit `(itemClick)` event

### LINKED ISSUE #11197: 🐞 - `SelectOption` fails to handle `click` event listener
### Reproduction url

https://stackblitz.com/edit/tui-select-option-broken-click

### Description

```ts
import { TuiSelectOption } from '@taiga-ui/kit';
// [...]
providers: [tuiAsOptionContent(TuiSelectOption)],
```

```html
<tui-textfield [(open)]="open" (click)="open.set(true)">
  <input tuiTextfield />

  <tui-data-list *tuiTextfieldDropdown>
    <button tuiOption new (click)="log($event)" [value]="42">No logs</button>
    <button tuiOption new (click)="log($event)">Has logs</button>
  </tui-data-list>
</tui-textfield>
```

Removing `this.open.set(false)` from `handleOption` "fixes" bug. 
https://github.com/taiga-family/taiga-ui/blob/0c75661b12bd8eb202307a2ebcd5f023876eabb4/projects/core/components/textfield/textfield.component.ts#L182-L185

### Taiga UI version

4.42.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by nsbarsukov**
Fixes #11197

### CODE REVIEW

File: projects/core/components/textfield/textfield.component.ts [hunk 1]
```diff
@@ -181,7 +181,9 @@ export class TuiTextfieldComponent<T> implements TuiDataListHost<T>, AfterConten
 
     public handleOption(option: T): void {
         this.accessor?.setValue(option);
-        this.open.set(false);
+        // Ensure all external (click) handlers are called before closing dropdown
+        // <button tuiOption (click)="..." />
+        setTimeout(() => this.open.set(false));
```
Comment (splincode) [inline projects/core/components/textfield/textfield.component.ts]: what do you think? 

```ts
delay(0).pipe(takeUntilDestroyed(this.destroyRef)).subscribe(
 () => this.open.set(false)
);
```

Comment (waterplea) [reply projects/core/components/textfield/textfield.component.ts]: We decided it is not necessary for such cases

**Review by mdlufy — APPROVED** [review]
