### PR TITLE
fix(kit): correct open dropdown in textfield

### LINKED ISSUE #11275: 🐞 - `SelectLike` does not open dropdown on `Chevron` click (directly on icon)
### Description

https://taiga-ui.dev/components/textfield#dropdown

https://github.com/user-attachments/assets/5ad77efd-3118-489d-8345-5183f2b473ed

BUT (without bug)
https://taiga-ui.dev/components/select/API

https://github.com/user-attachments/assets/adf10514-e248-40b7-959e-344c86f72e13

### Taiga UI version

4.44.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by splincode**
Fixes #11275

### CODE REVIEW

**Review by mdlufy — APPROVED** [review]

File: projects/core/components/textfield/textfield.component.ts [hunk 1]
```diff
@@ -171,7 +171,7 @@ export class TuiTextfieldBaseComponent<T>
 
         if (
             !this.dropdownOpen.tuiDropdownEnabled ||
-            !this.cva?.interactive() ||
+            !(this.cva?.interactive() ?? this.control?.enabled) ||
```
Comment (waterplea) [inline projects/core/components/textfield/textfield.component.ts]: Do we even need this line? Wouldn't the next line cover this case? 🤔

Comment (splincode) [reply projects/core/components/textfield/textfield.component.ts]: Before:

`this.cva` is undefined -> `this.cva?.interactive()` ->  `!(undefined)` -> if (true)


After:

`this.cva ?? this.control` -> is (undefined ?? {enabled: true}) ->  `!(undefined ?? true)` -> if (false)

Comment (waterplea) [reply projects/core/components/textfield/textfield.component.ts]: I mean if it's not interactive then next line would match anyway, I think we can just remove this line altogether.

Comment (splincode) [reply projects/core/components/textfield/textfield.component.ts]: However it's interactive 🤔 or I don't understand what is mean interactive mode

image
image

**Review by waterplea — APPROVED** [review]
