### PR TITLE
fix(kit): `Combobox` return null support for strict matcher

### LINKED ISSUE #5433: 🐞 - ComboBox placeholder bug
### Playground Link

https://taiga-ui.tcsbank.ru/components/combo-box/API?strictMatcher=null&sandboxExpanded=true

### Description

[Taiga-UI-Proprietary-ComboBox.webm](https://github.com/taiga-family/taiga-ui/assets/53703949/b1b5cba2-e8c4-4b67-8887-8491a536ad86)

### Angular version

_No response_

### Taiga UI version

_No response_

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #5433

### CODE REVIEW

File: projects/demo/src/modules/components/combo-box/combo-box.component.ts [hunk 1]
```diff
@@ -115,8 +115,9 @@ export class ExampleTuiComboBoxComponent extends AbstractExampleTuiControl {
 
     stringify = this.stringifyVariants[0];
 
-    readonly strictMatcherVariants: ReadonlyArray<TuiStringMatcher<Account>> = [
+    readonly strictMatcherVariants: ReadonlyArray<TuiStringMatcher<Account> | null> = [
         TUI_STRICT_MATCHER as TuiStringMatcher<Account>,
+        null,
```
Comment (waterplea) [inline projects/demo/src/modules/components/combo-box/combo-box.component.ts:120]: We don't need it explicitly in the list, null in type would enable cleaner on the docs

File: projects/kit/components/combo-box/combo-box.component.ts [hunk 2]
```diff
@@ -220,7 +220,9 @@ export class TuiComboBoxComponent<T>
     }
 
     private isStrictMatch(item: T): boolean {
-        return this.strictMatcher(item, this.search || '', this.stringify);
+        return this.strictMatcher
```
Comment (waterplea) [inline projects/kit/components/combo-box/combo-box.component.ts:223]: !!this.strictMatcher &&

**Review by splincode — APPROVED** [review]

**Review by waterplea — APPROVED** [review]
