### PR TITLE
fix(core): `DropdownOpen` fix initial open state

### LINKED ISSUE #9224: 🐞 - Select - dropdown content is not shown if initial state is opened
### Code Example URL

https://stackblitz.com/edit/angular-az8rzh?file=src/app/app.template.html,src/app/app.component.ts

### Description

Use case is to open a dropdown menu for select automatically. I used `[tuiDropdownOpen]` which is coming from `TuiDropdownOpenLegacy` directive but for some reason it's not working (sorry didn't have time to debug more). 

In provided example the problem is that dropdown open state is updated automatically to `false`. And also interesting example where `tuiDropdownOpenChange` is not used, please check here https://stackblitz.com/edit/angular-az8rzh-auyhbj?file=src%2Fapp%2Fapp.template.html.

In this case select is focused and arrow icon remains in the position when dropdown is opened, but dropdown content is not shown

image

### Taiga UI version

4.8.1

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by waterplea**
Fixes #9224

### CODE REVIEW

**Review by nsbarsukov — APPROVED** [review]

**Review by vladimirpotekhin — APPROVED** [review]

File: projects/legacy/directives/legacy-dropdown-open-monitor/legacy-dropdown-open-monitor.ts [hunk 1]
```diff
@@ -9,27 +10,30 @@ import {distinctUntilChanged} from 'rxjs';
...
-        .subscribe((open) => this.external?.tuiDropdownOpenChange.next(open));
+    public ngAfterViewInit(): void {
+        this.external?.tuiDropdownOpenChange
+            .pipe(distinctUntilChanged(), takeUntilDestroyed(this.destroyRef))
+            .subscribe((open) => {
+                if (open) {
+                    tuiGetClosestFocusable({
+                        initial: this.el,
+                        root: this.el,
+                    })?.focus();
```
Comment (vladimirpotekhin) [inline projects/legacy/directives/legacy-dropdown-open-monitor/legacy-dropdown-open-monitor.ts:29]: screenshot is suspicious
