### PR TITLE
fix(kit): `InputDate` fix closing parent dropdown

### LINKED ISSUE #11101: 🐞 - `tuiInputDate` closes the dropdown after selecting a date
### Reproduction url

https://stackblitz.com/edit/angular-nhb47vcp-4kd9nezx

### Description

After selecting a date, the dropdown closes. This does not happen, for example, with `tuiSelect`

### Taiga UI version

4.40.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
Fixes #11101

### CODE REVIEW

**Review by splincode — APPROVED** [review]

**Review by mdlufy — APPROVED** [review]

File: projects/kit/components/input-date/input-date.directive.ts [hunk 1]
```diff
@@ -120,7 +120,10 @@ export abstract class TuiInputDateBase<
         const subscription = this.calendar()?.valueChange.subscribe((value: any) => {
             this.onChange(value);
             this.open.set(false);
-            this.el.blur();
+
+            if (!this.el.closest('tui-dropdown')) {
```
Comment (mdlufy) [inline projects/kit/components/input-date/input-date.directive.ts:124]: Can we not rely on element string name?

Comment (vladimirpotekhin) [reply projects/kit/components/input-date/input-date.directive.ts:124]: I don't want to add an extra constant
