### PR TITLE
fix(kit): Safari bug where line clamp ellipsis doesn't hide properly

### LINKED ISSUE #11853: 🐞 - TuiLineClamp always shows dots in Safari
### Reproduction url

-

### Description

Hi! I found a bug with lineclamp in Safari, when its content has display block, then dots always shown (its only in Safari).
Here is [repo](https://github.com/KrollikRoddzer/lineclamp-taiga-ui-bug/tree/master/bug-reproduction) where i reproduced bug.

### Taiga UI version

4.52.0

### Browser Used

Safari

### OS Used

macOS

### PR DESCRIPTION
**Pull request by splincode**
Fixes #11853

### CODE REVIEW

File: projects/kit/components/line-clamp/line-clamp.component.ts [hunk 1]
```diff
@@ -113,7 +106,7 @@ export class TuiLineClamp implements DoCheck, AfterViewInit {
     }
 
     public ngAfterViewInit(): void {
-        this.initialized.set(true);
```
Comment (waterplea) [inline projects/kit/components/line-clamp/line-clamp.component.ts:116]: I think we can drop it in favor of `TuiTransitioned` host directive

File: projects/kit/components/line-clamp/line-clamp.component.ts [hunk 2]
```diff
@@ -66,12 +62,9 @@ export class TuiLineClamp implements DoCheck, AfterViewInit {
 
     private readonly options = inject(TUI_LINE_CLAMP_OPTIONS);
     private readonly el = tuiInjectElement();
-    private readonly cd = inject(ChangeDetectorRef);
+    private readonly style = this.el.style;
```
Comment (waterplea) [inline projects/kit/components/line-clamp/line-clamp.component.ts]: I don't think we need it

File: projects/kit/components/line-clamp/line-clamp.component.ts [hunk 3]
```diff
@@ -124,22 +117,26 @@ export class TuiLineClamp implements DoCheck, AfterViewInit {
...
         return this.options.showHint && this.overflown ? this.content : '';
     }
 
-    protected updateView(): void {
-        this.cd.detectChanges();
-    }
-
-    private update(): void {
+    protected update(): void {
         if (this.outlet) {
```
Comment (waterplea) [inline projects/kit/components/line-clamp/line-clamp.component.ts]: Maybe early return instead? Since this is just for type safety

File: projects/kit/components/line-clamp/line-clamp.component.ts [hunk 4]
```diff
@@ -124,22 +117,26 @@ export class TuiLineClamp implements DoCheck, AfterViewInit {
...
-            this.height.set(this.outlet.nativeElement.scrollHeight);
+            this.style.height = tuiPx(this.outlet.nativeElement.scrollHeight);
         }
 
-        this.maxHeight.set(this.lineHeight * this.linesLimit$.value);
+        this.style.maxHeight = tuiPx(this.lineHeight * this.linesLimit$.value);
+
+        if (this.overflown) {
+            this.el.classList.add('_overflown');
```
Comment (waterplea) [inline projects/kit/components/line-clamp/line-clamp.component.ts]: Use classList.toggle

File: projects/kit/components/line-clamp/line-clamp.component.ts [hunk 5]
```diff
@@ -124,22 +117,26 @@ export class TuiLineClamp implements DoCheck, AfterViewInit {
         const {scrollHeight, scrollWidth} = this.outlet.nativeElement;
         const {clientWidth} = this.el;
 
-        return scrollHeight > this.maxHeight() || scrollWidth > clientWidth;
+        return (
+            scrollHeight > parseFloat(this.style.maxHeight) || scrollWidth > clientWidth
```
Comment (waterplea) [inline projects/kit/components/line-clamp/line-clamp.component.ts]: nit: maybe save maxHeight to a const to avoid wrapping return to multiple lines for readibility?

**Review by waterplea — APPROVED** [review]

**Review by mdlufy — APPROVED** [review]

File: projects/kit/components/line-clamp/line-clamp.component.ts (hunk 1 above)
Comment (splincode) [reply projects/kit/components/line-clamp/line-clamp.component.ts:116]: fixed

File: projects/kit/components/line-clamp/line-clamp.component.ts (hunk 2 above)
Comment (splincode) [reply projects/kit/components/line-clamp/line-clamp.component.ts]: fixed

File: projects/kit/components/line-clamp/line-clamp.component.ts (hunk 3 above)
Comment (splincode) [reply projects/kit/components/line-clamp/line-clamp.component.ts]: fixed

File: projects/kit/components/line-clamp/line-clamp.component.ts (hunk 4 above)
Comment (splincode) [reply projects/kit/components/line-clamp/line-clamp.component.ts]: fixed

File: projects/kit/components/line-clamp/line-clamp.component.ts (hunk 5 above)
Comment (splincode) [reply projects/kit/components/line-clamp/line-clamp.component.ts]: fixed

File: projects/demo/src/modules/components/line-clamp/examples/1/index.html [hunk 6]
```diff
@@ -32,7 +32,7 @@
 
 <div
     *ngIf="value$ | async as value; else loading"
-    class="wrapper"
+    class="wrapper tui-space_bottom-4"
```
Comment (waterplea) [inline projects/demo/src/modules/components/line-clamp/examples/1/index.html:50]: We want to drop global styles in v5, let's not use those classes in newer code

Comment (splincode) [reply projects/demo/src/modules/components/line-clamp/examples/1/index.html:50]: fixed
