### PR TITLE
fix(core): ensure textfield filler respects RTL mode

### LINKED ISSUE #13550: 🐞 - `Textfield` supports RTL for `[filler]` property
https://taiga-ui.dev/components/textfield/API?filler=HH:MM

Image

### PR DESCRIPTION
**Pull request by splincode**
Fixes #13550

### CODE REVIEW

File: projects/core/components/textfield/textfield.component.ts [hunk 1]
```diff
@@ -93,10 +95,27 @@ export class TuiTextfieldBaseComponent<T>
     protected readonly icons = inject(TUI_COMMON_ICONS);
     protected readonly clear = toSignal(inject(TUI_CLEAR_WORD));
 
+    protected readonly isRtl = computed(() => {
```
Comment (waterplea) [inline projects/core/components/textfield/textfield.component.ts]: No need for this, we can use `this.el.matches('[dir="rtl"] :scope')`, we do it in other places already.

Comment (splincode) [reply projects/core/components/textfield/textfield.component.ts]: fixed

**Review by waterplea — APPROVED** [review]

File: projects/demo-playwright/tests/core/textfield/textfield-filler-rtl.pw.spec.ts [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+test.describe('Textfield filler in RTL mode', () => {
+    test('renders filler correctly in LTR and RTL', async ({page}) => {
+        await tuiGoto(page, `${DemoRoute.Textfield}/API?filler=HH:MM`);
+
+        const api = new TuiDocumentationApiPagePO(page);
+        const example = api.apiPageExample;
+        const input = example.locator('input[tuiTextfield]');
+
+        await input.focus();
+        await input.pressSequentially('123');
```
Comment (nsbarsukov) [inline projects/demo-playwright/tests/core/textfield/textfield-filler-rtl.pw.spec.ts]:
```suggestion
        await input.pressSequentially('12:3');
```

File: projects/demo-playwright/tests/core/textfield/textfield-filler-rtl.pw.spec.ts [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+        await expect.soft(example).toHaveScreenshot('input-filler-ltr.png');
+        await input.clear();
+        await example.evaluate((node) => node.setAttribute('dir', 'rtl'));
+        await input.focus();
+        await input.pressSequentially('123');
```
Comment (nsbarsukov) [inline projects/demo-playwright/tests/core/textfield/textfield-filler-rtl.pw.spec.ts]:
```suggestion
        await input.pressSequentially('12:3');
```

File: projects/demo-playwright/tests/core/textfield/textfield-filler-rtl.pw.spec.ts [hunk 4]
```diff
@@ -0,0 +1,22 @@
+import {DemoRoute} from '@demo/routes';
+import {TuiDocumentationApiPagePO, tuiGoto} from '@demo-playwright/utils';
+import {expect, test} from '@playwright/test';
+
+test.describe('Textfield filler in RTL mode', () => {
+    test('renders filler correctly in LTR and RTL', async ({page}) => {
+        await tuiGoto(page, `${DemoRoute.Textfield}/API?filler=HH:MM`);
+
+        const api = new TuiDocumentationApiPagePO(page);
+        const example = api.apiPageExample;
```
Comment (nsbarsukov) [inline projects/demo-playwright/tests/core/textfield/textfield-filler-rtl.pw.spec.ts]:
```suggestion
        const example = new TuiDocumentationApiPagePO(page).apiPageExample;
```
