### PR TITLE
fix(schematics): migrate `[disabled]`/`[readOnly]` from legacy controls to inner inputs

### LINKED ISSUE #13991: 🐞 - Invalid migration for `[disabled]` on legacy controls
### Reproduction url

https://github.com/taiga-family/maskito/blob/f7234e8eceb9323d0bccd507fff3d91cc254d5f2/projects/demo/src/pages/frameworks/angular/examples/2-nested/template.html#L17-L22

## v4 state
```html
<tui-input
    [disabled]="!show"
    [(ngModel)]="value"
>
    Name on the card
</tui-input>
```

## Migrated state
```html
<!-- TODO: (Taiga UI migration) tui-input migration (see https://taiga-ui.dev/components/input):
     - "[disabled]" is an unrecognized attribute and was placed on <tui-textfield>. Move it to <input tuiInput> if it targets the native element.
-->
<tui-textfield [disabled]="!show">
<label tuiLabel>Name on the card</label>
<input tuiInput [(ngModel)]="value" />
</tui-textfield>

```

## Expected v5
```html
<tui-textfield>
<label tuiLabel>Name on the card</label>
<input tuiInput [(ngModel)]="value" [disabled]="!show" />
</tui-textfield>
```
https://taiga-ui.dev/components/input#states

**Relates to ALL types of legacy controls!**
**Not only for `tui-input`!**

### Taiga UI version

5.4.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by nsbarsukov**
Fixes #13991

### CODE REVIEW

File: projects/cdk/schematics/ng-update/v5/steps/templates/migrate-multi-select.ts [hunk 1]
```diff
@@ -149,6 +156,15 @@ export function migrateMultiSelect({
             removeAttr(recorder, templateOffset, element, attr.name, template);
         });
 
+        // Remove control-state attrs from element (they go on <input>)
+        removeControlStateAttrs(
```
Comment (nsbarsukov) [inline projects/cdk/schematics/ng-update/v5/steps/templates/migrate-multi-select.ts]:
```suggestion
        removeControlStateAttrs(
```

**Review by splincode — APPROVED** [review]

**Review by vladimirpotekhin — APPROVED** [review]
