### PR TITLE
fix(core): expose dropdown hover state via public getter

### LINKED ISSUE #13714: 🐞 - Cannot determine hover status in `TuiDropdownHover`
### Reproduction url

none

### Description

In the [previous version](https://github.com/taiga-family/taiga-ui/blob/v4.x/projects/core/directives/dropdown/dropdown-hover.directive.ts#L93) of `TuiDropdownHover` directive, the `hovered` property was public, allowing external components/directives to read the current hover state of the dropdown. In 5.0.0 the `hovered` property was [changed ](https://github.com/taiga-family/taiga-ui/blob/main/projects/core/portals/dropdown/dropdown-hover.directive.ts#L43) to `private`.

**Expected behavior:** The hover state should be accessible externally, either by making the property public again or by exposing a public getter/observable.

### Taiga UI version

5.0.0

### Browser Used

Chrome

### OS Used

Windows

### PR DESCRIPTION
**Pull request by diwakar-2112**
Fixes #13714 

 Exposed the hover state via a public getter to make it accessible externally.

### CODE REVIEW

File: projects/core/portals/dropdown/dropdown-hover.directive.ts [hunk 1]
```diff
@@ -41,6 +40,9 @@ export class TuiDropdownHover extends TuiDriver {
     });
 
     private hovered = false;
```
Comment (waterplea) [inline projects/core/portals/dropdown/dropdown-hover.directive.ts]: I think it's better to make it:
```ts
public readonly hovered: Signal<boolean> = signal(false);
```
and use it as:
```ts
(this.hovered as WritableSignal<boolean>).set(hovered);
```
on line 78

Comment (diwakar-2112) [reply projects/core/portals/dropdown/dropdown-hover.directive.ts]: ok sure will update

**Comment by diwakar-2112** [comment]
@waterplea Addressed your suggestion in [2c23dc8] . Please review.

**Review by waterplea — COMMENTED** [review]
LGTM, just address the linting issues please

**Review by waterplea — APPROVED** [review]

**Review by splincode — APPROVED** [review]
