### PR TITLE
fix(core): `DropdownHover` fix dropdown closing after child transition

### LINKED ISSUE #5197: 🐞 - tooltip overlap the dialog
### Playground Link

https://stackblitz.com/edit/angular-da2xyd?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.less&hideExplorer=1

### Description

When i hover the tooltip and I'm trying to call dialog, tooltip remains on the same place. It's reproducible only on safari.

Video for reproducing:

https://github.com/taiga-family/taiga-ui/assets/16825894/670295fa-7cd5-45ec-96e3-e64ca27e4e14

### Angular version

15.2.0

### Taiga UI version

3.38.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behavior?

https://github.com/taiga-family/taiga-ui/issues/5395#issuecomment-1743010657

closes #5197

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/core/directives/hint/hint-hover.directive.ts [hunk 1]
```diff
@@ -29,6 +29,7 @@ export class TuiHintHoverDirective extends TuiDriver {
             repeat(),
         ),
     ).pipe(
+        map(value => !tuiGetElementObscures(this.el.nativeElement)?.length && value),
```
Comment (waterplea) [inline projects/core/directives/hint/hint-hover.directive.ts:32]: Change the order so the easiest to compute condition is first. This way we will not need to compute obscurers for falsy values. Also lets move it below `filter`.

File: projects/core/directives/hint/hint.component.ts [hunk 2]
```diff
@@ -108,8 +109,9 @@ export class TuiHintComponent<C = any> {
     @HostListener('document:click', ['$event.target'])
     onClick(target: HTMLElement): void {
         if (
-            !this.el.nativeElement.contains(target) &&
-            !this.hover.el.nativeElement.contains(target)
+            (!this.el.nativeElement.contains(target) &&
+                !this.hover.el.nativeElement.contains(target)) ||
+            tuiGetElementObscures(this.hover.el.nativeElement)?.length
```
Comment (waterplea) [inline projects/core/directives/hint/hint.component.ts:114]: Can you describe this scenario please?

Comment (vladimirpotekhin) [reply projects/core/directives/hint/hint.component.ts:114]: yes, this PR solves two scenarios (you can check it [here](https://taiga-ui.dev/components/dialog#directive)):

1. If hint already displayed when we click the button. `click` event bubbles to document => hint is obscured by dialog => close hint (most common case for desktop safari). This code is for this case

2. On mobile, hint doesn't appear until we tap the button, `document.click` handler doesn't work for this case. So we have to check after "hover" if is hint obscured.  `map(value => value && !tuiGetElementObscures(this.el.nativeElement)?.length)` is for this case.

**Review by waterplea — APPROVED** [review]
