### PR TITLE
fix(core): synchronize driver's state

### LINKED ISSUE #9941: 🐞 - Unable to open tuiDropdownContext menu after manually closing it
### Reproduction url

https://taiga-ui.dev/directives/dropdown-context#basic

### Description

Steps to reproduce:

1. RMB on the gear icon
2. Close dropdown via X button
3. RMB on the gear icon again

Expected behavior:

- Context menu opens again

Actual:

- Context menu doesn't open

The only way to open it again is to click anywhere else beforehand.

Found in v3, same behavior in v4.

### Taiga UI version

4.17.0

### Browser Used

Chrome

### OS Used

Windows

### PR DESCRIPTION
**Pull request by splincode**
Fixes #9941

### CODE REVIEW

**Review by waterplea — APPROVED** [review]

File: projects/core/directives/dropdown/dropdown.directive.ts [hunk 1]
```diff
@@ -112,5 +120,9 @@ export class TuiDropdownDirective
             this.ref.set(null);
             this.service.remove(ref);
         }
+
+        this.drivers
+            .filter((driver) => driver?.type === this.type)
```
Comment (waterplea) [inline projects/core/directives/dropdown/dropdown.directive.ts:125]: No need to check the type as they are all dropdown drivers. However sometimes directives provide themselves as drivers like `TuiDropdownSelection` or `TuiDropdownHover`. Let's put `TODO` on line 59 to think of a better solution later, I suppose it's good enough for now.

**Review by waterplea — APPROVED** [review]

File: projects/core/directives/dropdown/dropdown.directive.ts (hunk 1 above)
Comment (splincode) [reply projects/core/directives/dropdown/dropdown.directive.ts]: fixed

**Review by mdlufy — APPROVED** [review]
