### PR TITLE
fix(schematics): preserve label content when migrating legacy control with inner `<input>`

### LINKED ISSUE #13992: 🐞 - Invalid migration for legacy control label
### Reproduction url

https://github.com/taiga-family/maskito/blob/f7234e8eceb9323d0bccd507fff3d91cc254d5f2/projects/demo/src/pages/documentation/plugins/examples/3-change-event/component.ts#L12-L24

## Migration 

```html
<tui-input
        [maskito]="maskitoOptions"
        [style.max-width.rem]="20"
        [(ngModel)]="value"
>
    Enter number

    <input
            tuiTextfieldLegacy
            [maskito]="maskitoOptions"
            (change)="log($event)"
    />
</tui-input>
```

⬇️ 

```html
<tui-textfield [maskito]="maskitoOptions" [style.max-width.rem]="20">
    <input
            tuiInput
            [maskito]="maskitoOptions"
            (change)="log($event)" [(ngModel)]="value"/>
</tui-textfield>
```

## Expected migrated state

```html
<tui-textfield [maskito]="maskitoOptions" [style.max-width.rem]="20">
    <label tuiLabel>Enter number</label>
    <input
            tuiInput
            placeholder="Enter number"
            [maskito]="maskitoOptions"
            (change)="log($event)" [(ngModel)]="value"/>
</tui-textfield>
```

### Taiga UI version

5.4.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by nsbarsukov**
Fixes #13992

### CODE REVIEW

File: projects/cdk/schematics/ng-update/v5/steps/templates/migrate-input.ts [hunk 1]
```diff
@@ -527,16 +527,61 @@ function migrateInnerInput({
...
-    const siblings = allChildren
-        .filter((c) => c !== inner)
+    const labelContent = buildLabelContent(parent, inner, template);
+    const labelHtml = labelContent
+        ? `${indent}<label tuiLabel>${labelContent}</label>\n`
+        : '';
+
+    const innerStart = innerLoc.startOffset;
+    const siblingsAfter = parent.childNodes
+        .filter((c): c is Element => {
```
Comment (splincode) [inline projects/cdk/schematics/ng-update/v5/steps/templates/migrate-input.ts]: please, use `child` instead of `c`

**Review by splincode — APPROVED** [review]

File: projects/cdk/schematics/ng-update/v5/steps/templates/migrate-input.ts (hunk 1 above)
Comment (nsbarsukov) [reply projects/cdk/schematics/ng-update/v5/steps/templates/migrate-input.ts]: https://github.com/taiga-family/taiga-ui/pull/14008/commits/a3d74954c5f3c66c4753674519e9be240a796fef

Comment (nsbarsukov) [reply projects/cdk/schematics/ng-update/v5/steps/templates/migrate-input.ts]: Missed one more, I'll fix it too

Comment (nsbarsukov) [reply projects/cdk/schematics/ng-update/v5/steps/templates/migrate-input.ts]: https://github.com/taiga-family/taiga-ui/pull/14008/commits/a3d74954c5f3c66c4753674519e9be240a796fef

**Review by vladimirpotekhin — APPROVED** [review]
