### PR TITLE
fix(core): close dropdown when dropdown host is hidden via css

### LINKED ISSUE #9121: 🐞 - Position accessor
### Code Example URL

Nothing

### Description

https://github.com/user-attachments/assets/d3d1223e-bbd4-4d9f-b3e6-e2d77fedd9c8

### Taiga UI version

latest

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
Close #9121

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/core/directives/dropdown/dropdown.component.ts [hunk 1]
```diff
@@ -66,14 +66,16 @@ export class TuiDropdownComponent {
...
+                () => this.directive.el.isConnected && !!this.directive.el.offsetParent,
+            ),
             map((v) => (this.directive.position === 'fixed' ? this.vvs.correct(v) : v)),
             map(([top, left]) => this.getStyles(top, left)),
             takeUntilDestroyed(),
         )
         .subscribe({
             next: (styles) => Object.assign(this.el.style, styles),
-            complete: () => this.close(),
+            complete: () => this.close?.(),
```
Comment (vladimirpotekhin) [inline projects/core/directives/dropdown/dropdown.component.ts:78]: `?` is for jest-tests  (because of order)

**Review by waterplea — APPROVED** [review]
