### PR TITLE
fix(kit): update a tab when the active index has changed

### LINKED ISSUE #4918: 🐞 - `TabsWithMore` button "More" becomes unavailable after change activeItemIndex
### Playground Link

https://taiga-ui.dev/v2/navigation/tabs#more

### Problem
The button "More" moves to the right  and becomes unavailable when you select tab from dropdown via activeItemIndex.
### How to reproduce
https://taiga-ui.dev/v2/navigation/tabs#more

- Go to [docs](https://taiga-ui.dev/v2/navigation/tabs#more)

- Set width `div t-example` ~360px
image

- Set `activeItemIndex >= 2`
image

### Angular version

11.2.14

### Taiga UI version

2.58.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by splincode**
## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #4918

## What is the new behavior?

https://github.com/taiga-family/taiga-ui/assets/12021443/931e7a14-a56c-473a-9cb7-3d9800000cf4

### CODE REVIEW

File: projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts [hunk 1]
```diff
@@ -58,8 +58,10 @@ export class TuiTabsWithMoreComponent implements AfterViewInit {
     @HostBinding('class._underline')
     underline = this.options.underline;
 
-    @Input()
-    activeItemIndex = 0;
+    @Input('activeItemIndex')
+    set itemIndex(index: number) {
+        this.updateActiveItemIndex(index);
```
Comment (waterplea) [inline projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts:63]: This method emits back "changes" output. Would it cause any issues?

**Review by waterplea — APPROVED** [review]

File: projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts (hunk 1 above)
Comment (vladimirpotekhin) [reply projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts:63]: maybe 
```
this.activeItemIndex = activeItemIndex;
this.maxIndex = this.getMaxIndex();
```
?

Comment (splincode) [reply projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts]: fixed

**Review by nsbarsukov — APPROVED** [review]
