### PR TITLE
fix(kit): `ComboBox` with virtual scroll resets form control value on scroll

### LINKED ISSUE #11403: 🐞 - `ComboBox` with virtual scroll resets form control value on scroll
### Reproduction url

https://taiga-ui.dev/components/combo-box#virtual-scroll

### Description

1. Open https://taiga-ui.dev/components/combo-box#virtual-scroll
2. Select first item (`Andorra`) from datalist (dropdown will be automatically closed)
3. Click on the textfield to open dropdown again
4. Scroll datalist until `Andorra` will be replaced by new items in DOM

**Expected behavior:** form control still contains `Andorra`
**Actual behavior:** form control is patched with `null`

### Relates
https://github.com/taiga-family/taiga-ui/blob/4d0aaa1164d88e77c332e97cc2091920730b8720/projects/kit/components/combo-box/combo-box.directive.ts#L84-L85

With virtual scroll options are dynamically updated on scroll (new datalist items replace previous ones)

Bug reported initially here https://t.me/taiga_ui/7924/31462

### Taiga UI version

4.46.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by nsbarsukov**
Fixes #11403

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/kit/components/combo-box/combo-box.directive.ts [hunk 1]
```diff
@@ -159,7 +169,7 @@ export class TuiComboBox<T>
         }
     }
 
-    private stringify(value: T | string | null): string {
+    private stringify(value: T | string | null | undefined): string {
```
Comment (waterplea) [inline projects/kit/components/combo-box/combo-box.directive.ts]: value?:

**Review by waterplea — APPROVED** [review]

File: projects/kit/components/combo-box/combo-box.directive.ts (hunk 1 above)
Comment (nsbarsukov) [reply projects/kit/components/combo-box/combo-box.directive.ts]: https://github.com/taiga-family/taiga-ui/pull/11413/commits/c34031ba18cc5892f5d21419aceb5f28fd3aacf5
