### PR TITLE
fix(kit): skeleton animation speed slow down after speed up TUI_ANIMA…

### LINKED ISSUE #9778: 🐞 - TuiSkeleton animation speed slow down after speed up TUI_ANIMATIONS_SPEED
### Reproduction url

https://stackblitz.com/edit/angular-qoqwp3?file=src%2Fapp%2Fapp.template.html

### Description

When you speed up animations TUI_ANIMATIONS_SPEED, the animation speed of TuiSkeleton (maybe something else) slows down a lot.

### Taiga UI version

4.15.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by Jonesso**
Fixes #9778

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/kit/directives/skeleton/skeleton.directive.ts [hunk 1]
```diff
@@ -39,8 +42,9 @@ class TuiSkeletonStyles {}
 export class TuiSkeleton implements OnChanges {
     private animation?: Animation;
     private readonly el = tuiInjectElement();
-    private readonly duration =
-        inject(TUI_ANIMATIONS_SPEED) * TUI_ANIMATIONS_DEFAULT_DURATION * 2;
+    private readonly duration = tuiGetDuration(
+        inject(TUI_ANIMATIONS_SPEED) * TUI_ANIMATIONS_DEFAULT_DURATION * 2,
```
Comment (waterplea) [inline projects/kit/directives/skeleton/skeleton.directive.ts:46]: You do not need `TUI_ANIMATIONS_DEFAULT_DURATION`, it is already there in `tuiGetDuration`. What was intended here, I believe, it to have duration twice longer than regular animations. So you need to change this to `tuiGetDuration(inject(TUI_ANIMATION_SPEED) * 2`

**Review by vladimirpotekhin — APPROVED** [review]
