### PR TITLE
fix(addon-charts): `LineDaysChart` fix performance leak

### LINKED ISSUE #5482: 🐞 - LineDaysChart page perfomance issues when use tui-input
### Playground Link

https://angular-ern3ir.stackblitz.io

### Description

I have two LineDaysChart on my page + several inputs. When i write text to my inputs page has performance issues in Chome but no issues in Safari browser. For some reason this problem does not appear in my stackblitz example.

### Angular version

14.2.9

### Taiga UI version

3.29.2

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by waterplea**
## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #5482

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/core/directives/hint/hint-describe.directive.ts [hunk 1]
```diff
@@ -53,12 +62,18 @@ export class TuiHintDescribeDirective extends TuiDriver {
         super(subscriber => this.stream$.subscribe(subscriber));
     }
 
+    ngOnChanges() {
```
Comment (nsbarsukov) [inline projects/core/directives/hint/hint-describe.directive.ts:65]:
```suggestion
    ngOnChanges(): void {
```

Comment (nsbarsukov) [reply projects/core/directives/hint/hint-describe.directive.ts:65]: Screenshot 2023-09-28 at 10 38 02

**Review by nsbarsukov — APPROVED** [review]
:slozno:

**Review by vladimirpotekhin — APPROVED** [review]
