### PR TITLE
fix(kit): `InputFiles` fix validity and drag states

### LINKED ISSUE #8840: 🐞 - `InputFiles` no longer updates control validity
### Playground Link

_No response_

### Description

The new `tuiInputFiles` directive does not set control state to invalid.

### Angular version

18.2

### Taiga UI version

4

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### LINKED ISSUE #8841: 🐞 - `InputFiles` no longer updates `dragged` state when file is dragged outside of drop area
### Playground Link

_No response_

### Description

The issue can be seen in the [Custom Content](https://taiga-ui.dev/components/input-files#custom) demo. If you drag a file on top of the drop area and then move it outside, the drop area state is not updated.

### Angular version

18.2

### Taiga UI version

4

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### LINKED ISSUE #8842: 🐞 - `InputFiles` documentation code link leads to `404` page
### Playground Link

_No response_

### Description

`InputFiles` documentation code link needs to be updated.

### Angular version

_No response_

### Taiga UI version

_No response_

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by waterplea**
Close #8840
Close #8841
Close #8842

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/demo/src/modules/components/input-files/examples/1/index.ts [hunk 1]
```diff
@@ -16,7 +16,11 @@ import {finalize, map, of, Subject, switchMap, timer} from 'rxjs';
     changeDetection,
 })
 export default class Example {
-    protected readonly control = new FormControl<TuiFileLike | null>(null);
+    protected readonly control = new FormControl<TuiFileLike | null>(
+        null,
+        Validators.required,
```
Comment (vladimirpotekhin) [inline projects/demo/src/modules/components/input-files/examples/1/index.ts:21]: Input becomes invalid immediately after the first click - is this expected?

**Review by vladimirpotekhin — APPROVED** [review]
