### PR TITLE
fix: update arc chart value input handling

### LINKED ISSUE #12232: 🚀 - Hacktoberfest special
### Description

As we are approaching v5 we need to migrate all inputs and outputs to signals so that the public API is ready for the first alpha release. It would be a great help if community can assist us with this. It should be pretty straightforward but there's a lot of components to go through.

### PR DESCRIPTION
**Pull request by robmanganelly**
Fixes #12232 

PARTIAL FIX : https://github.com/taiga-family/taiga-ui/issues/12232

This PR contains the fix for arc-chart component
Subsequent PRs will address other files. I tried changing one component at a time to prevent large batches.

##  Changes in this PR

changed inputs and outputs to use signal api
changed viewChildren to use signal api
cleaned up some redundancies 
added documentation to make explicit to consumers that internal state of the component can change some values
moved signal reads to template variables on top (easier to spot, read once use many)

## Problems

ESLint rules sometimes are forcing incorrect patterns. I skipped lint of the affected line on each case and documented the reason

## Chance for improvement

using native `@for` and template variables + computations could make the component even more reactive. Did not pursue because it was outside the scope of the ticket. 

will be paying attention to comments  and resolution before starting the next component

### CODE REVIEW

File: projects/addon-charts/components/arc-chart/arc-chart.component.ts [hunk 1]
```diff
@@ -44,75 +38,72 @@ function arcsToIndex(arcs: QueryList<ElementRef<SVGElement>>): Array<Observable<
...
-        .subscribe(() => this.initialized.set(true));
+    private readonly indexChange$ = toObservable(this.arcs).pipe(
+        takeUntilDestroyed(),
+        // keep spread to remove readonly constraint
+        switchMap((arcs) =>
+            merge(...arcsToIndex([...arcs])).pipe(
+                tap((i) => this.activeItemIndex.set(i)),
+            ),
+        ),
+    );
```
[the remark this answers is not in the document]
Comment (robmanganelly) [reply projects/addon-charts/components/arc-chart/arc-chart.component.ts:55]: replaced spread with type assertion , see fix commits

File: projects/addon-charts/components/arc-chart/arc-chart.component.ts [hunk 2]
```diff
@@ -44,75 +38,72 @@ function arcsToIndex(arcs: QueryList<ElementRef<SVGElement>>): Array<Observable<
...
 
-    @Input()
-    public value: readonly number[] = [];
+    protected readonly initialized = toSignal(
+        timer(0).pipe(
+            tuiZonefree(),
+            take(1),
+            // The linter rule 'no-restricted-syntax' incorrectly flags 'map(() => true)' here,
```
Comment (splincode) [inline projects/addon-charts/components/arc-chart/arc-chart.component.ts:61]: you can use `TUI_TRUE_HANDLER`

File: projects/addon-charts/components/arc-chart/arc-chart.template.html [hunk 3]
```diff
@@ -1,5 +1,8 @@
+@let v = value();
```
Comment (splincode) [inline projects/addon-charts/components/arc-chart/arc-chart.template.html]: or `@let data = value();`

Comment (robmanganelly) [reply projects/addon-charts/components/arc-chart/arc-chart.template.html]: feedback addressed in 
[b4a8c42](https://github.com/taiga-family/taiga-ui/pull/12250/commits/b4a8c424409e57c6d1f7d6936d0a4145f6b3241d)

File: projects/addon-charts/components/arc-chart/arc-chart.component.ts (hunk 2 above)
Comment (robmanganelly) [reply projects/addon-charts/components/arc-chart/arc-chart.component.ts:61]: `TUI_TRUE_HANDLER` type is too narrow for this.
type `true` !== type `boolean`

I left a more direct comment initially but copilot review asked me to replace it with what you see now.
please see attached pictures. 

Screenshot 2025-10-14 at 10 21 34 AM

Screenshot 2025-10-14 at 10 21 52 AM

Screenshot 2025-10-14 at 10 24 09 AM

I could always hack the initial value's type, but that seems dirty, skipping es-lint seemed the preferred solution because it is both technically correct and cleaner.

Please let me know your preference

Comment (splincode) [reply projects/addon-charts/components/arc-chart/arc-chart.component.ts:61]: okey, no problem
