### PR TITLE
fix(core): `tuiDropdownHover` closes immediately when hovered and clicked simultaneously

### LINKED ISSUE #13434: 🐞 - tuiDropdownHover closes immediately when hovered and clicked simultaneously.
### Reproduction url

https://taiga-ui.dev/directives/dropdown-hover#dropdown-open

### Description

https://github.com/user-attachments/assets/12253dfc-5913-4fad-b294-86d9c6175edf

### Taiga UI version

latest

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by splincode**
Fixes #13434

### CODE REVIEW

File: projects/core/directives/dropdown/dropdown-hover.directive.ts [hunk 1]
```diff
@@ -69,7 +69,15 @@ export class TuiDropdownHover extends TuiDriver {
     ).pipe(
         map((element) => tuiIsElement(element) && this.isHovered(element)),
         distinctUntilChanged(),
-        switchMap((v) => of(v).pipe(delay(v ? this.showDelay : this.hideDelay))),
+        switchMap((visible) => {
```
Comment (waterplea) [inline projects/core/directives/dropdown/dropdown-hover.directive.ts]: Maybe like that? Also no need for typed method, let's use built-in rxjs one

```ts
switchMap((visible) => of(visible).pipe(
  delay(visible ? this.showDelay : this.hideDelay),
  takeUntil(fromEvent(this.el, visible ? 'pointerdown' : 'click'),
)
```

Comment (splincode) [reply projects/core/directives/dropdown/dropdown-hover.directive.ts]: fixed
