### PR TITLE
fix(core): do not emit onChange on initialization of TuiItemsHandlersValidator

### LINKED ISSUE #11907: 🐞 - TuiInputDate emits initial value of the passed control
### Reproduction url

https://stackblitz.com/edit/angular-cxuffoxm-mi5h18rs?file=src%2Fapp%2Fapp.template.html

### Description

When subscribing to .valueChanges of the control that is passed inside tuiInputDate, it emits the initial value of the control.

### Taiga UI version

4.53.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by pwespi**
Fixes #11907

### CODE REVIEW

File: projects/core/directives/items-handlers/items-handlers.validator.ts [hunk 1]
```diff
@@ -13,10 +13,16 @@ import {TuiItemsHandlersDirective} from './items-handlers.directive';
 })
 export class TuiItemsHandlersValidator extends TuiValidator {
     private readonly handlers = inject(TuiItemsHandlersDirective);
+    private initialized = false;
 
     protected readonly update = effect(() => {
```
Comment (splincode) [inline projects/core/directives/items-handlers/items-handlers.validator.ts:18]: @pwespi Could you write a test to make sure this code fixes the bug and works as expected?

Comment (pwespi) [reply projects/core/directives/items-handlers/items-handlers.validator.ts:18]: I added a test

**Comment by splincode** [comment]
@pwespi thank you so much, so, could you add a cherry pick to main?

**Comment by pwespi** [comment]
> @pwespi thank you so much, so, could you add a cherry pick to main?

Here it is: https://github.com/taiga-family/taiga-ui/pull/13176
