### PR TITLE
fix(cdk): when the consumer unsubscribes, clean up data ready for next subscription

### LINKED ISSUE #6553: 🐞 - tuiControlValue memory leak
### Playground Link

_No response_

### Description

You subscribe to a control in `tuiControlValue` function, but do not unsubscribe when the source observable completes or is unsubscribed.

Here is the source code:

```
export function tuiControlValue<T>(
    control: AbstractControl | AbstractControlDirective,
): Observable<T> {
    return new Observable(subscriber => {
        if (!control.valueChanges) {
            throw new TuiValueChangesException();
        }

        control.valueChanges.pipe(startWith(control.value)).subscribe(subscriber);
    });
}
```

### Angular version

_No response_

### Taiga UI version

_No response_

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by splincode**
Closes #6553

### CODE REVIEW

**Review by vladimirpotekhin — APPROVED** [review]

File: projects/cdk/observables/control-value.ts [hunk 1]
```diff
@@ -13,6 +13,10 @@ export function tuiControlValue<T>(
             throw new TuiValueChangesException();
         }
 
-        control.valueChanges.pipe(startWith(control.value)).subscribe(subscriber);
+        const subscription = control.valueChanges
+            .pipe(startWith(control.value))
+            .subscribe(subscriber);
+
+        return () => subscription.unsubscribe();
```
Comment (waterplea) [inline projects/cdk/observables/control-value.ts:20]: You can just add `return`, the subscription is a valid teardown logic.

**Review by waterplea — APPROVED** [review]

File: projects/cdk/observables/control-value.ts (hunk 1 above)
Comment (splincode) [reply projects/cdk/observables/control-value.ts]: fixed
