### PR TITLE
fix(kit): fix tree programmatic control

### LINKED ISSUE #2658: 🐞 - `Tree` programmatic control problems
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/tree-programatic-control-bug?file=src/app/app.component.html

### Is this issue blocking you?

Non-Blocking

### Description

1. Open https://stackblitz.com/edit/tree-programatic-control-bug?file=src/app/app.component.html
2. Press "Toggle Topmost" button
3. Press "Toggle Child №1" button
4. Press "Toggle Child №2" button

**Expected behaviour:**
expected

**Actual behaviour:**
actual
(the second child is still collapsed)

5. Press "Toggle Topmost" button
6. Press "Toggle Topmost" button (again, yep)
(all children are opened despite the fact that the second child was collapsed on the previous step. It is expected behaviour).
result

### Angular version

any

### Taiga UI version

3.1.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #2658

### CODE REVIEW

File: projects/demo/src/modules/components/tree/examples/4/index.ts [hunk 1]
```diff
@@ -39,7 +39,7 @@ export class TuiTreeExample4 {
         ],
     };
 
-    readonly map = new Map<TreeNode, boolean>();
+    map = new Map<TreeNode, boolean>();
```
Comment (splincode) [inline projects/demo/src/modules/components/tree/examples/4/index.ts:42]: why?

**Review by splincode — APPROVED** [review]

**Review by waterplea — APPROVED** [review]
