### PR TITLE
fix(core): `Dialog` should hide close icon if `closeable` equals to `Observable<false>`

### LINKED ISSUE #8204: 🐞 - TuiDialogComponent async closeable
### Playground Link

_No response_

### Description

Требуется запрещать пользователю закрывать окно в течении 10 секунд

TuiDialogOptions.closeable может быть Observable. Но код dialog.template.html не содержит async для *ngIf="context.closeable"

```
canClose$ = of(false)

dialogService
          .open(WaitingBankDialogComponent, {
            closeable: canClose$,
            dismissible: canClose$,
          })
```
Не работает

Решение

1. Добавить в ts TuiDialogComponent
`  readonly closeable$ = toObservable(this.context.closeable);`

2. Изменить темплейт
c
`<div *ngIf="context.closeable"  class="t-wrapper">`
на
`<div *ngIf="closeable$ | async" class="t-wrapper">`

### Angular version

18.0.6

### Taiga UI version

3.85.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by nsbarsukov**
https://taiga-ui.dev/components/dialog#prompt

https://github.com/taiga-family/taiga-ui/blob/8f071226dcb9e4893b2d2a4bcf23fd6490e01456/projects/core/components/dialog/dialog.interfaces.ts#L22

Closes #8204

### CODE REVIEW

File: projects/core/components/dialog/dialog.component.ts [hunk 1]
```diff
@@ -71,10 +71,11 @@ export class TuiDialogComponent<O, I> {
 
     protected readonly closeWord$ = inject(TUI_CLOSE_WORD);
     protected readonly icons = inject(TUI_COMMON_ICONS);
+    protected closeable$ = toObservable(this.context.closeable);
```
Comment (nsbarsukov) [inline projects/core/components/dialog/dialog.component.ts:74]: Probably, I should add `share()` 🤔

**Review by splincode — APPROVED** [review]

**Review by vladimirpotekhin — APPROVED** [review]
