### PR TITLE
fix(experimental): use valid content children from template into `tui-accordion`

### LINKED ISSUE #10414: 🐞 - Accordion (EXPERIMENTAL). Errors in the console when changing data
### Reproduction url

https://stackblitz.com/edit/angular-89rh5rzc?file=src%2Fapp%2Fapp.template.html

### Description

Errors in the console when changing data
`Error: Cannot set properties of undefined (setting 'expanded')`
Errors in this line
`this.expands.get(this.directives.toArray().indexOf(d))!.expanded = d.open();`

### Taiga UI version

4.24.0

### Browser Used

Chrome

### OS Used

Windows

### PR DESCRIPTION
**Pull request by splincode**
Fixes #10414

### CODE REVIEW

File: projects/experimental/components/accordion/accordion.component.ts [hunk 1]
```diff
@@ -57,25 +57,33 @@ export class TuiAccordionComponent implements AfterViewInit {
     }
 
     public ngAfterViewInit(): void {
-        this.toggle$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe((d) => {
-            if (this.closeOthers && d.open()) {
-                this.expands.forEach((expand) => {
-                    expand.expanded = false;
-                });
+        this.toggle$
+            .pipe(delay(0), takeUntilDestroyed(this.destroyRef))
```
Comment (mdlufy) [inline projects/experimental/components/accordion/accordion.component.ts:61]: Why we need hack `delay(0)`?

**Review by mdlufy — APPROVED** [review]

File: projects/experimental/components/accordion/accordion.component.ts (hunk 1 above)
Comment (splincode) [reply projects/experimental/components/accordion/accordion.component.ts:61]: there, without delay, old nodes are returned in the query list, which is why undefined was returned here and an error occurred in runtime

**Review by waterplea — APPROVED** [review]
