### PR TITLE
fix(legacy): add tuiUnfinishedValidator behaviour for InputDateTimeComponent

### LINKED ISSUE #6513: 🐞 - tuiUnfinishedValidator in tuiInputDateTime
### Playground Link

_No response_

### Description

I want to replicate the behavior of tuiUnfinishedValidator from tuiInputDate to tuiInputDateTime, but this is impossible

### Angular version

17.0.0

### Taiga UI version

3.56.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by LarisaGl**
Closes #6513

### CODE REVIEW

**Comment by LarisaGl** [comment]
Based on comments in https://github.com/taiga-family/taiga-ui/pull/6731

File: projects/legacy/components/input-date-time/input-date-time.component.ts [hunk 1]
```diff
@@ -319,20 +330,28 @@ export class TuiInputDateTimeComponent
...
         const parsedTime = TuiTime.fromString(time);
 
-        this.value = [this.value[0], parsedTime];
+        this.value = [this.value ? this.value[0] : null, parsedTime];
     }
 
-    protected getFallbackValue(): [TuiDay | null, TuiTime | null] {
-        return [null, null];
+    protected getFallbackValue(): [TuiDay | null, TuiTime | null] | null {
+        return this.tuiUnfinishedValidator ? null : [null, null];
```
Comment (waterplea) [inline projects/legacy/components/input-date-time/input-date-time.component.ts:337]: There's no need to inject the unfinished validator. We just need to treat `null` as `null` and not as `[null, null]`. See my other comments

File: projects/legacy/components/input-date-time/input-date-time.component.ts [hunk 2]
```diff
@@ -183,7 +188,7 @@ export class TuiInputDateTimeComponent
         }
 
         if (value.length < DATE_FILLER_LENGTH) {
-            this.value = [null, null];
+            this.value = this.tuiUnfinishedValidator ? null : [null, null];
```
Comment (waterplea) [inline projects/legacy/components/input-date-time/input-date-time.component.ts:191]: What we want to do in `onValueChange` is this:
1) If it's just the date, set value to `[parsedDate, null]`
2) If it's complete date + time set it to `[parsedDate, parsedTime]`
3) Set it to `null` in all other cases (i.e. `12.12.2`, `12.12.2012, 1`, `12.12.2012, 12:` etc.

This way we will have `null` in all _unfinished_ states and unfinished validator will automatically work as expected.

Comment (LarisaGl) [reply projects/legacy/components/input-date-time/input-date-time.component.ts:191]: Ok, got it. I tried to save previous behaviour and add new one just in case of tuiUnfinishedValidator using. Then I'll fix it as default behaviour without tuiUnfinishedValidator. Thanks for review!

Comment (LarisaGl) [reply projects/legacy/components/input-date-time/input-date-time.component.ts]: Fixed! You can check it out. I hope it's correct now :)

File: projects/legacy/components/input-date-time/input-date-time.component.ts (hunk 1 above)
Comment (LarisaGl) [reply projects/legacy/components/input-date-time/input-date-time.component.ts]: Done, I have removed it

File: projects/legacy/components/input-date-time/native-date-time/native-date-time.directive.ts [hunk 3]
```diff
@@ -20,7 +20,10 @@ export class TuiNativeDateTimeDirective {
     protected readonly host = inject(TuiInputDateTimeDirective);
 
     protected get value(): string {
-        if (!this.host.rawValue[0] || !this.host.rawValue[1]) {
+        if (
+            !this.host.rawValue ||
+            (this.host.rawValue && (!this.host.rawValue[0] || !this.host.rawValue[1]))
```
Comment (waterplea) [inline projects/legacy/components/input-date-time/native-date-time/native-date-time.directive.ts:25]: `if (!this.host.rawValue?.[0] || !this.host.rawValue?.[1]) {`
Would that work?

Comment (LarisaGl) [reply projects/legacy/components/input-date-time/native-date-time/native-date-time.directive.ts]: Sure, fixed

File: projects/legacy/components/input-date-time/input-date-time.component.ts [hunk 4]
```diff
@@ -116,10 +117,10 @@ export class TuiInputDateTimeComponent
         });
 
     @Input()
-    public min: TuiDay | [TuiDay | null, TuiTime | null] | null = this.options.min;
+    public min: TuiDay | [TuiDay, TuiTime | null] | null = this.options.min;
```
[the remark this answers is not in the document]
Comment (LarisaGl) [reply projects/legacy/components/input-date-time/input-date-time.component.ts]: Yes, I tried. You could check new version

[the remark this answers is not in the document]
Comment (waterplea) [reply projects/legacy/components/input-date-time/input-date-time.component.ts]: I mean it used to be `[TuiDay | null, TuiTime | null]` and now `TuiDay` is required. These are public inputs and people might have them typed `[TuiDay | null, TuiTime | null]` and it would cause errors for them. Can we keep it `[TuiDay | null, TuiTime | null]` whenever possible?

[the remark this answers is not in the document]
Comment (waterplea) [reply projects/legacy/components/input-date-time/input-date-time.component.ts]: So if `value[0] === null` treat it just as if `value === null`

File: projects/legacy/components/input-date-time/input-date-time.component.ts [hunk 5]
```diff
@@ -254,7 +259,7 @@ export class TuiInputDateTimeComponent
 
         return (
             this.month ||
-            this.value[0] ||
+            (this.value ? this.value[0] : null) ||
```
Comment (waterplea) [inline projects/legacy/components/input-date-time/input-date-time.component.ts:262]: this.value?.[0]

Comment (LarisaGl) [reply projects/legacy/components/input-date-time/input-date-time.component.ts]: fixed

File: projects/legacy/components/input-date-time/input-date-time.component.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (LarisaGl) [reply projects/legacy/components/input-date-time/input-date-time.component.ts]: sure, fixed

**Review by waterplea — APPROVED** [review]

**Review by splincode — APPROVED** [review]

**Review by vladimirpotekhin — APPROVED** [review]
