### PR TITLE
fix(kit): `InputTime`, `InputDate`, `InputMonth` with native picker ignore initial form control value

### LINKED ISSUE #11457: 🐞 - `InputDate` with native picker ignores initial form control value
### Reproduction url

https://stackblitz.com/edit/tui-input-date-native-picker-initial-form-control-value

### Description

Open StackBlitz of this example (Angular 18):
https://taiga-ui.dev/components/input-date#datalist

Bug is not reproducible.

___

Upgrade to Angular 19
https://stackblitz.com/edit/tui-input-date-native-picker-initial-form-control-value
Bug is reproducible 

___
`writeValue` and subsequent `tuiValue` is executed before host binding

https://github.com/taiga-family/taiga-ui/blob/7f926393a3462483d5d20cb8e92cc4a35be32ad6/projects/kit/components/input-date/input-date.component.ts#L24

Relates:
* https://github.com/angular/angular/pull/57874

### Taiga UI version

4.46.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by nsbarsukov**
Fixes #11457

### CODE REVIEW

File: projects/core/components/textfield/with-native-picker.directive.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
+import {Directive} from '@angular/core';
+import {tuiInjectElement} from '@taiga-ui/cdk/utils/dom';
+
+/**
+ * Use it instead of host binding
+ * host: { '[type]': '"text"' }
+ * ___
+ * From Angular 19+ all effects are called before host bindings.
+ * If effects inside `tuiValue` will be called before `<input />` get `type="text"`,
+ * it will cause loosing initial value
```
Comment (nsbarsukov) [inline projects/core/components/textfield/with-native-picker.directive.ts]:
```suggestion
 * it will cause loss of initial value
```

File: projects/kit/components/input-date/input-date.directive.ts [hunk 2]
```diff
@@ -102,7 +103,9 @@ export abstract class TuiInputDateBase<
         onCleanup(() => subscription?.unsubscribe());
     });
 
-    public readonly native = this.el.type.includes('date') && this.mobile;
+    public readonly native =
+        Boolean(inject(TuiWithNativePicker, {optional: true})) && this.mobile;
```
Comment (waterplea) [inline projects/kit/components/input-date/input-date.directive.ts]: Why not `!!`?

File: projects/kit/components/input-month/input-month.directive.ts [hunk 3]
```diff
@@ -67,7 +67,7 @@ export class TuiInputMonthDirective extends TuiControl<TuiMonth | null> {
     );
 
     public readonly native =
-        tuiInjectElement<HTMLInputElement>().type === 'month' && inject(TUI_IS_MOBILE);
+        Boolean(inject(TuiWithNativePicker, {optional: true})) && inject(TUI_IS_MOBILE);
```
Comment (waterplea) [inline projects/kit/components/input-month/input-month.directive.ts]: Same

File: projects/kit/components/input-time/input-time.directive.ts [hunk 4]
```diff
@@ -96,7 +96,7 @@ export class TuiInputTimeDirective
     public accept: readonly TuiTime[] = [];
 
     public readonly native =
-        tuiInjectElement<HTMLInputElement>().type === 'time' && inject(TUI_IS_MOBILE);
+        Boolean(inject(TuiWithNativePicker, {optional: true})) && inject(TUI_IS_MOBILE);
```
Comment (waterplea) [inline projects/kit/components/input-time/input-time.directive.ts]: Same

**Review by waterplea — APPROVED** [review]

File: projects/kit/components/input-date/input-date.directive.ts (hunk 2 above)
Comment (nsbarsukov) [reply projects/kit/components/input-date/input-date.directive.ts]: https://github.com/taiga-family/taiga-ui/pull/11460/commits/a087c0d1047caeb25a9a5be382c6bd57f91ad500

**Review by splincode — APPROVED** [review]
