### PR TITLE
fix(kit): `Carousel` fix autoscroll in ssr

### LINKED ISSUE #10266: 🐞 - Carousel bag with [duration] | Баг карусели с использованием [duration]
### Reproduction url

https://stackblitz.com/run?file=src%2Fapp%2Fapp.template.html&hideExplorer=1

### Description

Не уверен как именно воспроизвести это на стек блиц, опишу подробно тут:
На проекте используется ssr. Просто используя карусель на странице - все окей, как только в карусель добавляем [duration]=500 например, или любое другое значение, страница перестает загружаться и выдает ошибку, что представлена на скриншоте.

**ПРИМЕЧАНИЕ:** Ловится только в том случае, если самый первый запуск или перезагрузка идет именно с той страницы, где присутствует эта карусель.

Image

Image

### Taiga UI version

4.21.0

### Browser Used

Edge

### OS Used

Windows

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
Fixes #10266

### CODE REVIEW

**Review by splincode — APPROVED** [review]

**Review by waterplea — APPROVED** [review]

File: projects/kit/components/carousel/carousel.directive.ts [hunk 1]
```diff
@@ -20,7 +22,12 @@ export class TuiCarouselDirective extends Observable<unknown> {
         this.visible$,
     );
 
-    private readonly output$ = combineLatest([this.duration$, this.running$]).pipe(
+    private readonly output$ = combineLatest([
```
Comment (waterplea) [inline projects/kit/components/carousel/carousel.directive.ts:25]: Should we instead do `isPlatformServer(...) ? EMPTY : ...` maybe, so to minimize effect on overall code?
