### PR TITLE
fix(core): `DropdownOpen` sync state when changed externally

### LINKED ISSUE #10784: 🐞 - `DropdownOpen` closing with handler is broken
### Reproduction url

https://stackblitz.com/edit/angular-sdyvfm85

### Description

Looks like this is newly introduced after this:
https://github.com/taiga-family/taiga-ui/pull/10592

### Taiga UI version

4

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by waterplea**
Fixes #10784

### CODE REVIEW

File: projects/core/directives/dropdown/dropdown-open.directive.ts [hunk 1]
```diff
@@ -117,6 +117,12 @@ export class TuiDropdownOpen implements OnChanges {
         )
         .subscribe(() => this.toggle(false));
 
+    public readonly sync = this.driver.pipe(takeUntilDestroyed()).subscribe((open) => {
+        if (open !== this.tuiDropdownOpen) {
+            this.update(open);
+        }
+    });
```
Comment (splincode) [inline projects/core/directives/dropdown/dropdown-open.directive.ts:124]: what if?

```ts
this.driver.pipe(
   filter((open) => open !== this.tuiDropdownOpen),
   takeUntilDestroyed()
).subscribe((open) => this.update(open));
```

**Review by splincode — APPROVED** [review]

**Review by mdlufy — APPROVED** [review]

**Review by vladimirpotekhin — APPROVED** [review]
