### PR TITLE
fix(legacy): `InputPhone` incorrectly parses paste of the shorten phone number

### LINKED ISSUE #9834: 🐞 - tui-input-phone Component doesn’t parse phone number if length is less than 13
### Reproduction url

https://taiga-ui.dev/components/input-phone/API?countryCode=%2B850

### Description

When I paste a phone number with 11 digits (e.g., +850 (555) 591-72) into the tui-input-phone component, the input doesn’t parse it correctly.

Expected Behavior:
The input should display the number exactly as pasted:
+850 (555) 591-72

Actual Behavior:
The component adds extra numbers at the beginning, resulting in:
+850 (850) 555-59-17

### Taiga UI version

4.16.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by shiv9604**
Fixes #9834 

Changes Description:-
1. Consider trimming the number with `trimCountryPrefix` in [`tuiCreateCompletePhoneInsertionPreprocessor`](https://github.com/taiga-family/taiga-ui/blob/main/projects/legacy/components/input-phone/utils/complete-phone-insertion-preprocessor.ts)  when the pasted phone number is with country code.

### CODE REVIEW

**Review by vladimirpotekhin — APPROVED** [review]

**Review by splincode — APPROVED** [review]

**Comment by splincode** [comment]
image

File: projects/legacy/components/input-phone/utils/complete-phone-insertion-preprocessor.ts [hunk 1]
```diff
@@ -40,12 +40,13 @@ export function tuiCreateCompletePhoneInsertionPreprocessor(
                      * and mask are ready to reject "extra" characters.
                      * We should cut leading country prefix to save trailing characters!
                      */
-                    countDigits(value) > completePhoneLength
+                    countDigits(value) > completePhoneLength ||
+                    value.startsWith(countryCode)
```
Comment (nsbarsukov) [inline projects/legacy/components/input-phone/utils/complete-phone-insertion-preprocessor.ts:44]: See failed screenshot test

image

**Review by nsbarsukov — CHANGES_REQUESTED** [review]

File: projects/legacy/components/input-phone/utils/complete-phone-insertion-preprocessor.ts (hunk 1 above)
Comment (nsbarsukov) [reply projects/legacy/components/input-phone/utils/complete-phone-insertion-preprocessor.ts:44]: Probably, we should add new condition `|| value.startsWith(countryCode)` only for `data` property

File: projects/legacy/components/input-phone/utils/complete-phone-insertion-preprocessor.ts [hunk 2]
```diff
@@ -40,12 +40,13 @@ export function tuiCreateCompletePhoneInsertionPreprocessor(
...
                         ? trimCountryPrefix(value)
                         : value,
             },
             data:
-                countDigits(data) >= completePhoneLength
+                countDigits(data) >= completePhoneLength || value.startsWith(countryCode)
```
Comment (nsbarsukov) [inline projects/legacy/components/input-phone/utils/complete-phone-insertion-preprocessor.ts:49]:
```suggestion
                countDigits(data) >= completePhoneLength || data.startsWith(countryCode)
```

File: projects/legacy/components/input-phone/utils/complete-phone-insertion-preprocessor.ts (hunk 1 above)
Comment (shiv9604) [reply projects/legacy/components/input-phone/utils/complete-phone-insertion-preprocessor.ts:44]: I agree! as that block only takes care of number processing on paste events.

Resolved!

File: projects/legacy/components/input-phone/utils/complete-phone-insertion-preprocessor.ts (hunk 2 above)
Comment (shiv9604) [reply projects/legacy/components/input-phone/utils/complete-phone-insertion-preprocessor.ts]: Resolved!

**Comment by shiv9604** [comment]
> image

Just wanted to confirm whether we should ensure test cases succees with jest before push is enough or we need to ensure e2e as well.

**Comment by splincode** [comment]
@shiv9604 just fix unit test please

**Comment by shiv9604** [comment]
> @shiv9604 just fix unit test please

Yeah @splincode, Working on the same & will publish the commit asap. Will keep you posted about same.

**Comment by splincode** [comment]
@shiv9604 Oh, sorry, my fault 

apparently this also needs to be fixed in e2e

image

**Review by nsbarsukov — APPROVED** [review]
