### PR TITLE
fix(legacy): display view/hide password button with `readOnly` property

### LINKED ISSUE #6973: 🐞 - tui-input-password does not display the view/hide password button
### Playground Link

https://stackblitz.com/edit/angular-n6jrjp?file=src%2Fapp%2Fapp.component.html

### Description

Can you add [showButtons] directory in 3-th version? Because readOnly attribute can't work with dynamic form.

### Angular version

17

### Taiga UI version

3.69

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by olegnowikow**
Closes #6973

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/legacy/components/input-password/input-password.component.ts [hunk 1]
```diff
@@ -67,7 +67,10 @@ export class TuiInputPasswordComponent
     }
 
     public get inputType(): string {
-        return this.isPasswordHidden || !this.interactive ? 'password' : 'text';
+        return this.isPasswordHidden ||
+            !(this.interactive || (this.readOnly && !this.computedDisabled))
```
Comment (waterplea) [inline projects/legacy/components/input-password/input-password.component.ts:71]: I believe interactive is a getter for not read-only && not disabled. Not computed disabled is enough to check. Same in template. Also please do this in both v3.x and main.

**Review by waterplea — APPROVED** [review]
