### PR TITLE
fix(kit): `Avatar` fix icon color for appearances

### LINKED ISSUE #10257: 🐞 - `Avatar` icon should use proper color
### Reproduction url

https://taiga-ui.dev/directives/appearance

### Description

Avatar's icon inherits text color, not icon color from appearance

### Taiga UI version

4

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by waterplea**
Fixes #10257

### CODE REVIEW

File: projects/core/directives/icons/icons.directive.ts [hunk 1]
```diff
@@ -35,7 +42,7 @@ export class TuiIcons {
     protected readonly resolver: TuiStringHandler<string> = tuiInjectIconResolver();
 
     @Input()
-    public iconStart = inject(TUI_ICON_START, {self: true, optional: true}) || '';
+    public iconStart: Icon = inject(TUI_ICON_START, {self: true, optional: true}) || '';
 
     @Input()
     public iconEnd = inject(TUI_ICON_END, {self: true, optional: true}) || '';
```
Comment (splincode) [inline projects/core/directives/icons/icons.directive.ts:48]: shouldn't be as consistent?

`public iconEnd: Icon`

**Review by splincode — APPROVED** [review]

File: projects/core/directives/icons/icons.directive.ts (hunk 1 above)
Comment (waterplea) [reply projects/core/directives/icons/icons.directive.ts:48]: No, no reason to add hack here

**Review by vladimirpotekhin — APPROVED** [review]
