### PR TITLE
fix(addon-table): fix sorting on table with dynamic columns

### LINKED ISSUE #6070: 🐞 -  sorting doesn't work on table with dynamic columns
### Playground Link

https://stackblitz.com/edit/angular-d2zgt1-gdy6wy?file=src%2Fapp%2Fapp.component.ts

### Description

колонка name - нескрываемая
1. Изменяем дефолтную сортировку по полю name на сортировку по полю age
2. Кликаем на чекбокс Select all, чтобы скрыть все колонки 
3. Кликаем на чекбокс email
4. Сортируем по полю email
5. Визуально как будто сортировка применилась, но **tuiSortByChange возвращает null**
6. Кликаем на чекбокс age
7. Визуально сортировка по двум полям (email, age), реально - по полю age

### Angular version

17.0.4

### Taiga UI version

3.55.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behaviour?

Closes #6070

### CODE REVIEW

File: projects/addon-table/components/table/directives/sortable.directive.ts [hunk 1]
```diff
@@ -29,12 +29,6 @@ export class TuiSortableDirective<T extends Partial<Record<keyof T, any>>>
         this.th.sorter = this.sorter;
     }
 
-    ngDoCheck(): void {
-        if (this.match && this.table.sorter !== this.sorter) {
-            this.table.updateSorter(this.sorter);
-        }
-    }
```
Comment (vladimirpotekhin) [inline projects/addon-table/components/table/directives/sortable.directive.ts:36]: @waterplea pay attention plz, it created some race (double updateSorter call), but I didn't see its purpose

**Review by splincode — APPROVED** [review]

**Review by waterplea — CHANGES_REQUESTED** [review]

File: projects/addon-table/components/table/directives/sortable.directive.ts (hunk 1 above)
Comment (vladimirpotekhin) [reply projects/addon-table/components/table/directives/sortable.directive.ts]: ok
I finally found the problem with doCheck

there are `match` getter in sortable directive, and first time after clicking on `th` there is a wrong value in `this.sortBy.tuiSortBy` https://github.com/taiga-family/taiga-ui/blob/main/projects/addon-table/components/table/directives/sortable.directive.ts#L39
I suggest manually kicking it after clicking on `Th`, then everything seems to be ok

File: projects/addon-table/components/table/th/th.component.ts [hunk 2]
```diff
@@ -52,6 +53,9 @@ export class TuiThComponent<T extends Partial<Record<keyof T, any>>> {
         @Optional()
         @Inject(forwardRef(() => TuiTableDirective))
         readonly table: TuiTableDirective<T> | null,
+        @Optional()
+        @Inject(forwardRef(() => TuiSortByDirective))
+        private readonly sortBy: TuiSortByDirective<T> | null,
```
Comment (waterplea) [inline projects/addon-table/components/table/th/th.component.ts:58]: SortBy directive is kind of an extension over the regular table API to allow sorting by key, baseline table should not depend on it.

Comment (vladimirpotekhin) [reply projects/addon-table/components/table/th/th.component.ts]: Ok, I reverted `Th` :+1:

now I tried to invert the flow a little:  we can call `check` and update parent table directive from `TuiSortByDirective` setter, instead of relying on ngDoCheck

**Review by waterplea — APPROVED** [review]
