### PR TITLE
fix(core): close `Hint` and `Dropdown` when host is detached from dom

### LINKED ISSUE #7531: 🐞 - Дропдауны и тултипы не скрываются, если хост пропал из дома
### Playground Link

https://stackblitz.com/edit/angular-e8yupy?file=src%2Fapp%2Fapp.component.html

### Description

У нас при переходе на другую страницу в приложении, из дома пропадают компоненты (но ngOnDestroy не происходит), в таком случае дропдауны и тултипы продолжают существовать, смещаясь в левый верхний угол. нужно чтобы они скрывались, если хоста нет в доме

### Angular version

15.x.x

### Taiga UI version

3.74.x

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
Closes #7531

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/core/directives/dropdown/dropdown.component.ts [hunk 1]
```diff
@@ -77,6 +77,12 @@ export class TuiDropdownComponent {
                 takeUntil(destroy$),
             )
             .subscribe(([top, left]) => {
+                if (!this.directive.el.nativeElement.isConnected) {
+                    this.directive.toggle(false);
+
+                    return;
```
Comment (waterplea) [inline projects/core/directives/dropdown/dropdown.component.ts:83]: else makes less lines :)

**Review by waterplea — APPROVED** [review]

File: projects/core/directives/dropdown/dropdown.component.ts [hunk 2]
```diff
@@ -79,11 +79,9 @@ export class TuiDropdownComponent {
             .subscribe(([top, left]) => {
                 if (!this.directive.el.nativeElement.isConnected) {
                     this.directive.toggle(false);
-
-                    return;
+                } else {
+                    this.update(top, left);
                 }
```
Comment (splincode) [inline projects/core/directives/dropdown/dropdown.component.ts:84]:
```ts
if (this.directive.el.nativeElement.isConnected) {
    this.update(top, left);
} else {
   this.directive.toggle(false); 
}
```

File: projects/core/directives/hint/hint.component.ts [hunk 3]
```diff
@@ -95,11 +95,9 @@ export class TuiHintComponent<C = any> {
             .subscribe(([top, left]) => {
                 if (!this.hover.el.nativeElement.isConnected) {
                     this.hover.toggle(false);
-
-                    return;
+                } else {
+                    this.update(top, left);
                 }
```
Comment (splincode) [inline projects/core/directives/hint/hint.component.ts:100]:
```ts
if (this.directive.el.nativeElement.isConnected) {
    this.update(top, left);
} else {
   this.directive.toggle(false); 
}
```
