### PR TITLE
fix(kit): `InputNumber` has rounding problems on blur with float large numbers

### LINKED ISSUE #9970: 🐞 - `tuiFormatNumber` utility has rounding problems with float large numbers
### Reproduction url

https://taiga-ui.dev/components/input-number/API

### Description

```ts
it('TODO', () => {
    expect(
        tuiFormatNumber(123456789012345.11, {
            precision: 2,
            thousandSeparator: '_',
        }),
    ).toBe('123_456_789_012_345.11');
});
```

Image

### Taiga UI version

4.18.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by nsbarsukov**
1. Open https://taiga-ui.dev/components/input-number/API?thousandSeparator=_&precision=2
2. Paste 
    ```
    123_456_789_012_345.67
    ```
3. Blur

**Previous behavior:** `123_456_789_012_345.69`
**New behavior:** `123_456_789_012_345.67`

Fixes #9970

### CODE REVIEW

File: projects/legacy/components/input-number/input-number.component.ts [hunk 1]
```diff
@@ -274,7 +274,15 @@ export class TuiInputNumberComponent
             this.computedPrefix +
             tuiFormatNumber(value, {
                 ...this.numberFormat,
-                precision: this.precision,
+                /**
+                 * Number can satisfy interval [Number.MIN_SAFE_INTEGER; Number.MAX_SAFE_INTEGER]
+                 * but its rounding can violate it.
+                 * Before BigInt support there are no perfect solution – only trade off.
```
Comment (nsbarsukov) [inline projects/legacy/components/input-number/input-number.component.ts:280]:
```suggestion
                 * Before BigInt support there is no perfect solution – only trade off.
```

File: .cspell.json [hunk 2]
```diff
@@ -3,7 +3,7 @@
     "import": ["@taiga-ui/cspell-config/cspell.config.js"],
     "files": ["*/*.*"],
     "ignorePaths": ["**/projects/i18n/languages/**", "**/addon-commerce/utils/get-currency-symbol.ts"],
-    "ignoreWords": ["Wachovia", "bottomsheet", "appbar", "qwertypgj_", "antialiasing", "xxxs"],
+    "ignoreWords": ["Wachovia", "bottomsheet", "appbar", "qwertypgj_", "antialiasing", "xxxs", "significand"],
```
Comment (waterplea) [inline .cspell.json:6]: It's «significant» with a T 🙂

File: projects/cdk/utils/math/round.ts [hunk 3]
```diff
@@ -23,9 +23,19 @@ function calculate(
...
+    const [significand, exponent = ''] = `${value}`.split('e');
+    const roundedInt = func(Number(`${significand}e${Number(exponent) + precision}`));
+
+    /**
+     * TODO: use BigInt after bumping Safari to 14+
+     */
+    ngDevMode &&
+        console.assert(
+            Number.isSafeInteger(roundedInt),
+            'Impossible to correctly round the such large number',
```
Comment (waterplea) [inline projects/cdk/utils/math/round.ts:35]: «the» is not needed, such A large number

**Review by waterplea — APPROVED** [review]

File: .cspell.json (hunk 2 above)
Comment (nsbarsukov) [reply .cspell.json:6]: https://en.wikipedia.org/wiki/Significand

File: projects/cdk/utils/math/round.ts (hunk 3 above)
Comment (nsbarsukov) [reply projects/cdk/utils/math/round.ts:35]:
```suggestion
            'Impossible to correctly round a such large number',
```

File: projects/cdk/utils/math/round.ts [hunk 4]
```diff
@@ -23,9 +23,19 @@ function calculate(
...
+    const [significand, exponent = ''] = `${value}`.split('e');
+    const roundedInt = func(Number(`${significand}e${Number(exponent) + precision}`));
+
+    /**
+     * TODO: use BigInt after bumping Safari to 14+
+     */
+    ngDevMode &&
+        console.assert(
+            Number.isSafeInteger(roundedInt),
+            'Impossible to correctly round a such large number',
```
Comment (nsbarsukov) [inline projects/cdk/utils/math/round.ts:35]:
```suggestion
            'Impossible to correctly round such a large number',
```

**Review by splincode — APPROVED** [review]

File: .cspell.json (hunk 2 above)
Comment (waterplea) [reply .cspell.json:6]: Damn! Ok :)
