### PR TITLE
fix(addon-mobile): `SheetDialog` add missing label divider

### LINKED ISSUE #5125: 🐞 - [SheetDialog] No bottom divider/border below label
### Playground Link

https://stackblitz.com/edit/angular-oq4wvt?file=src%2Fapp%2Fapp.component.ts

### Description

After changing from **TuiSheetModule** to **TuiSheetDialogModule**, there is no bottom divider/border below the sheet label, as it was with **tuiSheetHeading**. Not sure if it's a bug, but it changes the appearance of the sheet. 

Steps to reproduce: 
1. Add sheet from TuiSheetDialogModule (template way)
2. Add a label as a template or a string

In both cases, there is no divider below the label. 

Example:
```
HTML file

<ng-template #label>
    <label>And the Holy Grail</label>
</ng-template>

<ng-template
    [tuiSheetDialogOptions]="{  label: label }" // or by simple string
    [(tuiSheetDialog)]="open"
>
... sheet content
</ng-template>
```
image

### Angular version

16.0.0

### Taiga UI version

3.4.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behaviour?

Closes #5125

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts [hunk 1]
```diff
@@ -54,6 +60,11 @@ export class TuiSheetDialogComponent<I> implements AfterViewInit {
         },
     };
 
+    stuck$ = this.scroll$.pipe(
```
Comment (waterplea) [inline projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts:63]: How about we make it a behavior subject and next to it the actual boolean only if it changes? This way we get rid of the middle man.

Comment (vladimirpotekhin) [reply projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts]: done, take a look plz if I got you right

**Review by waterplea — APPROVED** [review]
