### PR TITLE
fix(kit): `InputDateRange` should not distinguish ranges with same dates and different names

### LINKED ISSUE #7909: 🐞 - `InputDateRange` doesn't switch between two items with same range
### Playground Link

https://stackblitz.com/edit/angular-edlp9k-vx84yw?file=src%2Fapp%2Fapp.component.html

### Description

Problem: `InputDateRange` does not switch correct between items with same ranges

https://github.com/taiga-family/taiga-ui/assets/87331898/7d99be02-a7b5-4015-a480-c8d0c7fd7707

### Angular version

16.2.12

### Taiga UI version

3.83.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by mdlufy**
Closes #7909

### CODE REVIEW

File: projects/kit/components/input-date-range/input-date-range.component.ts [hunk 1]
```diff
@@ -157,6 +168,20 @@ export class TuiInputDateRangeComponent
         super(control, cdr, valueTransformer);
     }
 
+    @HostListener('click')
+    onClick(): void {
+        if (!this.isMobile && this.interactive) {
+            this.toggle();
+        }
+    }
```
Comment (mdlufy) [inline projects/kit/components/input-date-range/input-date-range.component.ts:176]: due to linter moved up from https://github.com/taiga-family/taiga-ui/pull/7932/files#diff-f8d088649bf22db138c442a2d8eb5d993a48f02cc6d3ec29cd7a30fb299b655aL272-L278

File: projects/kit/components/input-date-range/input-date-range.component.ts [hunk 2]
```diff
@@ -157,6 +168,20 @@ export class TuiInputDateRangeComponent
...
+
+    ngAfterViewChecked(): void {
+        if (this.calendarRange) {
+            this.calendarRange.selectedActivePeriod = this.selectedActivePeriod;
+            this.calendarRange.checkUpdate();
+        }
```
Comment (mdlufy) [inline projects/kit/components/input-date-range/input-date-range.component.ts:182]: when calendar rerender pass saved `selectedActivePeriod` to child calendarRange to display correct active item

File: projects/kit/components/input-date-range/input-date-range.component.ts [hunk 3]
```diff
@@ -157,6 +168,21 @@ export class TuiInputDateRangeComponent
...
+        if (!this.isMobile && this.interactive) {
+            this.toggle();
+        }
+    }
+
+    // TODO: remove this after refactor controls to hold whole TuiDayRangePeriod
+    ngAfterViewChecked(): void {
+        if (this.calendarRange) {
+            this.calendarRange.selectedActivePeriod = this.selectedActivePeriod;
+            this.calendarRange.cdr.markForCheck();
```
Comment (mdlufy) [inline projects/kit/components/input-date-range/input-date-range.component.ts:182]: when calendar rerender, we need to pass saved `selectedActivePeriod` to child calendarRange displays correct active item

**Review by vladimirpotekhin — APPROVED** [review]

**Review by splincode — APPROVED** [review]
