### PR TITLE
fix(core): expression has changed after it was checked

### LINKED ISSUE #5798: 🐞 - ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for '_hosted_dropdown_focused': 'false'. Current value: 'true'
### Playground Link

_No response_

### Description

When a hosted dropdown has multiple submenus, sometimes the hover triggers this error ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for '_hosted_dropdown_focused': 'false'. Current value: 'true', the error pops up every now and then. In an empty project the error is given, but on stackblitz with identical code the error does not occur :)
image
Снимок экрана 2023-10-30 182004

### Angular version

16.2.6

### Taiga UI version

3.51.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by splincode**
## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behaviour?

Closes #5798
Closes https://github.com/taiga-family/taiga-ui/issues/4788

### CODE REVIEW

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts [hunk 1]
```diff
@@ -105,6 +129,13 @@ export class TuiHostedDropdownComponent implements TuiFocusableElementAccessor {
     @Input()
     canOpen = true;
 
+    readonly focused$ = this.focus$.pipe(
+        startWith(false),
+        map(() => this.focused),
+        distinctUntilChanged(),
+        takeUntil(this.destroy$),
```
Comment (waterplea) [inline projects/core/components/hosted-dropdown/hosted-dropdown.component.ts:136]: This is unnecessary since you do not subscribe.

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts [hunk 2]
```diff
@@ -105,6 +129,13 @@ export class TuiHostedDropdownComponent implements TuiFocusableElementAccessor {
     @Input()
     canOpen = true;
 
+    readonly focused$ = this.focus$.pipe(
+        startWith(false),
+        map(() => this.focused),
+        distinctUntilChanged(),
```
Comment (waterplea) [inline projects/core/components/hosted-dropdown/hosted-dropdown.component.ts:135]: This is unnecessary because it does not trigger change detection.

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts [hunk 3]
```diff
@@ -79,8 +97,14 @@ function shouldClose(
             useExisting: TuiHostedDropdownComponent,
         },
     ],
+    host: {
+        '[$.class._hosted_dropdown_focused]': 'focused$',
+        '($.class._hosted_dropdown_focused)': 'focused$',
+    },
 })
 export class TuiHostedDropdownComponent implements TuiFocusableElementAccessor {
+    private readonly focus$ = new Subject<boolean>();
```
Comment (waterplea) [inline projects/core/components/hosted-dropdown/hosted-dropdown.component.ts:106]: Just make it `BehaviorSubject(false)` and next `this.focused` to it.

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts (hunk 1 above)
Comment (splincode) [reply projects/core/components/hosted-dropdown/hosted-dropdown.component.ts]: fixed

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts (hunk 2 above)
Comment (splincode) [reply projects/core/components/hosted-dropdown/hosted-dropdown.component.ts]: fixed

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts (hunk 3 above)
Comment (splincode) [reply projects/core/components/hosted-dropdown/hosted-dropdown.component.ts]: fixed

**Review by waterplea — APPROVED** [review]

**Review by vladimirpotekhin — APPROVED** [review]
