### PR TITLE
fix(core): disable isObscured check for `HintPointer`

### LINKED ISSUE #7014: 🐞 - Hints are not working properly with `pie-chart`s & `ring-chart`s
### Playground Link

https://stackblitz.com/edit/angular-e8bpa7?file=src%2Fapp%2Fapp.component.html

### Description

If you add `[tuiHintContent]` to `<tui-ring-chart>` or `<tui-pie-chart>`, you'll notice that not all segments of the chart display hints, although it worked flawlessly earlier

Here you can see it in action:

https://github.com/taiga-family/taiga-ui/assets/55036936/b7dfafe9-064d-4687-94e7-82265757e383

Also, you might have noticed that hint appeared several times on hovering the "troubled-sections" in the video above...

Here i tried to reproduce & catch the hint on hovering again:

https://github.com/taiga-family/taiga-ui/assets/55036936/8fecb308-b22e-403f-81c0-54eb4f4ae1a5

### Angular version

16.2.12

### Taiga UI version

3.70.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
Closes #7014

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/core/directives/hint/hint-hover.directive.ts [hunk 1]
```diff
@@ -31,7 +31,12 @@ export class TuiHintHoverDirective extends TuiDriver {
         ),
     ).pipe(
         filter(() => this.enabled),
-        map(value => value && !tuiIsObscured(this.el.nativeElement)),
+        map(
+            value =>
+                value &&
+                (!tuiIsObscured(this.el.nativeElement) ||
```
Comment (waterplea) [inline projects/core/directives/hint/hint-hover.directive.ts:37]: Checking an attribute is cheaper, so move it in front.

**Review by waterplea — APPROVED** [review]
