### PR TITLE
fix(legacy): reuse `identityMatcher` inside `tuiMultiSelectGroup`

### LINKED ISSUE #10721: 🐞 - identityMatcher doesnot work in tuiMultiSelectGroup
### Reproduction url

https://stackblitz.com/edit/angular-rthgbrve?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.template.html

### Description

if we have complex object in controk,  tui-data-list-wrapper with tuiMultiSelectGroup in template and provide identityMatcher in providers, the checkbox does not active in multi select

### Taiga UI version

4.31

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by splincode**
Fixes #10721

### CODE REVIEW

File: projects/legacy/components/multi-select/multi-select-group/multi-select-group.directive.ts [hunk 1]
```diff
@@ -28,16 +29,24 @@ export const TUI_MULTI_SELECT_OPTION = new PolymorpheusComponent(
...
+                const {identityMatcher, stringify} =
+                    inject(TUI_ITEMS_HANDLERS, {optional: true}) ?? {};
 
                 return (
                     multiSelect || {
+                        stringify,
+                        identityMatcher,
                         handleOption: (option) => {
+                            const state = tuiArrayToggle(
+                                host ? host.value : ngControl.control?.value || [],
```
Comment (waterplea) [inline projects/legacy/components/multi-select/multi-select-group/multi-select-group.directive.ts:41]: Looks like we should make a const for this line:
```ts
const value = host?.value ?? ngControl.control?.value ?? [];
```

**Review by waterplea — APPROVED** [review]

File: projects/legacy/components/multi-select/multi-select-group/multi-select-group.directive.ts (hunk 1 above)
Comment (splincode) [reply projects/legacy/components/multi-select/multi-select-group/multi-select-group.directive.ts:41]: fixed

**Review by vladimirpotekhin — APPROVED** [review]
