### PR TITLE
fix(addon-table): hydration error while configuring table

### LINKED ISSUE #9278: 🐞 - Hydration error while configuring Table component
### Code Example URL

https://stackblitz.com/

### Description

image

```
@Component({
  selector: 'nx-suite-ui-table',
  standalone: true,
  imports: [
    AsyncPipe,
    NgTemplateOutlet,
    TuiTablePagination,
    TuiLet,
    TuiReorder,
    TuiTable,
    ToStringPipe,
    FormsModule,
    NgForOf,
    NgIf,
    ReactiveFormsModule,
    TuiButton,
    TuiChevron,
    TuiDropdown,
    TuiInputModule,
    TuiInputNumberModule,
    TuiLoader,
    TuiTextfieldControllerModule,
  ],
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NxSuiteUiTableComponent<T> implements TableComponent<T> {
  public readonly size = input.required<TableSize>();
  public readonly columns = input.required<TableColumnType<T>[]>();
  public readonly data = input.required<T[]>();
  public readonly contextMenu = input<any>();

  protected readonly sorter$ = new BehaviorSubject<any>('name');

  protected columns1 = ['id', 'name', 'description', 't'];

  protected readonly mappedColumns = computed(() =>
    this.columns().map((i) => i.field)
  );

  protected page = 3;
  protected size1 = 10;

  protected onPagination({ page, size }: TuiTablePaginationEvent): void {
    this.page = page;
    this.size1 = size;
  }
}
```
I am getting the following error with the defined structure:
image

I am using AnalogJS with SSR enabled.

### Taiga UI version

4.7.0

### Browser Used

Chrome

### OS Used

Windows

### PR DESCRIPTION
**Pull request by splincode**
Fixes #9278

### CODE REVIEW

File: projects/addon-table/components/table/th-group/th-group.component.ts [hunk 1]
```diff
@@ -24,6 +24,9 @@ import {TuiTableTh} from '../th/th.component';
     templateUrl: './th-group.template.html',
     changeDetection: ChangeDetectionStrategy.OnPush,
     providers: [TUI_TABLE_PROVIDER],
+    host: {
+        ngSkipHydration: 'true',
```
Comment (vladimirpotekhin) [inline projects/addon-table/components/table/th-group/th-group.component.ts:28]: > Be careful and thoughtful about using this attribute. It is intended as a last resort workaround. Components that break hydration should be considered bugs that need to be fixed.

please add a TODO to fix this later

Comment (splincode) [reply projects/addon-table/components/table/th-group/th-group.component.ts:35]: fixed

**Review by waterplea — APPROVED** [review]

**Review by vladimirpotekhin — APPROVED** [review]
