### PR TITLE
fix(core): `PrimitiveTextfield` with prefix/postfix has CD problem after delayed fonts loading

### LINKED ISSUE #5472: 🐞 - `PrimitiveTextfield` with prefix/postfix has change detection problem after delayed fonts loading
### Playground Link

https://stackblitz.com/edit/primitive-textfield-delayed-font-loading?file=src%2Fapp%2Fapp.component.html,src%2Findex.html

### Description

1. Throttle network request for fonts
2. Open https://stackblitz.com/edit/primitive-textfield-delayed-font-loading?file=src%2Fapp%2Fapp.component.html,src%2Findex.html

https://github.com/taiga-family/taiga-ui/assets/35179038/ca6378b9-3e4f-4e66-b90a-00142a18c999

___

Related problem:

___

https://github.com/taiga-family/taiga-ui/blob/3d0ca4e9d70ab04582cbd111b13ac42f5db1afae/projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts#L72-L75

### Angular version

12

### Taiga UI version

3.46.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by nsbarsukov**
## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #5472

### CODE REVIEW

File: projects/cdk/tokens/fonts-ready.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import {DOCUMENT} from '@angular/common';
+import {inject, InjectionToken} from '@angular/core';
+import {from, NEVER, Observable} from 'rxjs';
+import {shareReplay} from 'rxjs/operators';
+
+export const TUI_FONTS_READY = new InjectionToken<Observable<unknown>>(
+    `[TUI_FONTS_READY]`,
+    {
+        factory: () =>
+            from((inject(DOCUMENT) as any).fonts?.ready || NEVER).pipe(
```
Comment (nsbarsukov) [inline projects/cdk/tokens/fonts-ready.ts:10]: Guys, `NEVER` or `EMPTY` ? 🤔

Comment (splincode) [reply projects/cdk/tokens/fonts-ready.ts:10]: I think `EMPTY` prefer here

NEVER well… It never fires anything. It doesn’t emit anything nor does it complete the observable. This may be useful in very limited cases where you need to return a value, but you don’t want subscribers to act on it *or* for anyone to act on the observable completion. (c)

**Review by splincode — APPROVED** [review]

**Review by vladimirpotekhin — APPROVED** [review]

File: projects/cdk/tokens/fonts-ready.ts (hunk 1 above)
Comment (vladimirpotekhin) [reply projects/cdk/tokens/fonts-ready.ts:10]: I think `EMPTY`, because it terminates, and `NEVER` does not

**Review by waterplea — APPROVED** [review]
I don't think we need `refCount`. If everybody unsubscribes it would reset the stream and this event will never happen again. I think it's ok to keep it in the memory forever. Also let's go with `EMPTY` and then we can merge.

File: projects/cdk/tokens/fonts-ready.ts (hunk 1 above)
Comment (nsbarsukov) [reply projects/cdk/tokens/fonts-ready.ts]: fixed
