### PR TITLE
fix(core): `Dropdown` triggers change detection too frequently

### LINKED ISSUE #8725: 🐞 - `Dropdown` triggers change detection too frequently
### Playground Link

https://stackblitz.com/edit/dropdown-triggers-cd-too-frequently?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.template.html

### Description

<details>
<summary>
<strong>app.component.ts</strong>
</summary>

```ts
import { ChangeDetectionStrategy, Component, DoCheck } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { TuiDropdown, TuiLabel } from '@taiga-ui/core';
import { TuiSwitch } from '@taiga-ui/kit';

@Component({
  standalone: true,
  selector: 'app',
  templateUrl: './app.template.html',
  styleUrls: ['./app.style.less'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule, TuiSwitch, TuiLabel, TuiDropdown],
})
export class App implements DoCheck {
  open = false;

  ngDoCheck() {
    console.log('=[tick]=');
  }
}
```
</details>

<details open>
<summary>
<strong>app.template.html</strong>
</summary>

```html
<label tuiLabel>
  <input tuiSwitch type="checkbox" [(ngModel)]="open" />
  Show dropdown
</label>

<p
  class="host"
  tuiDropdownDirection="bottom"
  [tuiDropdown]="dropdownContent"
  [tuiDropdownManual]="open"
>
  Dropdown host
</p>

<ng-template #dropdownContent>
  Taiga UI is fully-treeshakable Angular UI Kit consisting of multiple base
  libraries and several add-ons. It is based on ng-polymorpheus dynamic content
  approach and uses Web APIs for Angular for required browser APIs.
</ng-template>
```
</details>

https://github.com/user-attachments/assets/ec77d5da-f8f6-4771-ab26-094130af2b0d

### Angular version

18

### Taiga UI version

4.4.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by nsbarsukov**
## Previous behavior

https://github.com/user-attachments/assets/b7fc0841-c23e-4746-9399-0d501bfd2f36

## New behavior

https://github.com/user-attachments/assets/a9fd6b0c-b96c-4559-ac27-85dd36e73d80

Close #8725

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/core/directives/dropdown/dropdown.directive.ts [hunk 1]
```diff
@@ -47,9 +54,10 @@ export class TuiDropdownDirective
     private readonly refresh$ = new Subject<void>();
     private readonly service = inject(TuiDropdownService);
     private readonly cdr = inject(ChangeDetectorRef);
+    private readonly zone = inject(NgZone);
```
Comment (waterplea) [inline projects/core/directives/dropdown/dropdown.directive.ts:57]: No need to store it on file, you can inject it directly where it's needed

File: projects/cdk/observables/zone.ts [hunk 2]
```diff
@@ -23,3 +28,32 @@ export function tuiZonefree<T>(zone: NgZone): MonoTypeOperatorFunction<T> {
...
+
+export function tuiZonefreeScheduler(
+    zone: NgZone,
+    scheduler: SchedulerLike = asyncScheduler,
+): SchedulerLike {
+    return new TuiZoneScheduler(zone.runOutsideAngular.bind(zone), scheduler);
+}
+
+export function tuiZonefullScheduler(
+    zone: NgZone,
```
Comment (waterplea) [inline projects/cdk/observables/zone.ts:55]: Let's write `= inject(NgZone)` here and in zone optimized functions so that we can just not pass it at place when they are in injection context

**Review by waterplea — APPROVED** [review]

**Review by waterplea — APPROVED** [review]
