### PR TITLE
fix(addon-mobile): add smooth opacity change for `MobileCalendar` to hide blinking initial view

### LINKED ISSUE #6456: 🐞 - `MobileCalendar` has blinking initial view
### Playground Link

https://stackblitz.com/edit/mobile-calendar-initial-blink-bug

### Description

1. Open any example in stackblitz (i.e. https://taiga-ui.dev/components/mobile-calendar#dropdown )
2. Set huge value for `TUI_ANIMATIONS_DURATION` (for convenient debug)
```ts
{
  provide: TUI_ANIMATIONS_DURATION,
  useValue: 5000,
},
```

(watch attentively at year section: `1902 => 2024` blink)

### Angular version

any

### Taiga UI version

3.62.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by nsbarsukov**
## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behaviour?
Closes #6456

### CODE REVIEW

File: projects/cdk/constants/version.ts [hunk 1]
```diff
@@ -1 +1 @@
-export const TUI_VERSION = `3.62.0`;
+export const TUI_VERSION = '3.62.0';
```
Comment (nsbarsukov) [inline projects/cdk/constants/version.ts:1]: It is not me 😄

**Review by splincode — APPROVED** [review]
