### PR TITLE
fix(cdk): Angular v19 `allowSignalWrites` warning

### LINKED ISSUE #9809: 🐞 - `allowSignalWrites: true` produces warning in Angular 19
### Reproduction url

https://github.com/taiga-family/taiga-ui/blob/432a4867f60c99fa266cd1bfaadf2e983d7c4984/projects/cdk/utils/miscellaneous/directive-binding.ts#L43

### Description

`allowSignalWrites: true` now results in a warning in Agular `19`:
```
The 'allowSignalWrites' flag is deprecated & no longer required for effect() (writes are allowed by default)
```

Warning is coming from the following code:
https://github.com/taiga-family/taiga-ui/blob/432a4867f60c99fa266cd1bfaadf2e983d7c4984/projects/cdk/utils/miscellaneous/directive-binding.ts#L43

### Taiga UI version

4.16.0

### Browser Used

Chrome

### OS Used

Windows

### PR DESCRIPTION
**Pull request by hakimio**
Fixes #9809

### CODE REVIEW

File: projects/cdk/utils/miscellaneous/directive-binding.ts [hunk 1]
```diff
@@ -18,30 +25,32 @@ export function tuiDirectiveBinding<
...
-            }
-
-            directive.ngOnChanges?.({});
-            output?.emit?.(value);
-            previous = value;
-        },
-        {allowSignalWrites: true},
-    );
+    effect(() => {
+        const value: any = result();
```
Comment (hakimio) [inline projects/cdk/utils/miscellaneous/directive-binding.ts:38]: All the `any` were here before. The only changed code is on lines 28-32.

**Review by splincode — APPROVED** [review]

**Comment by hakimio** [comment]
@vladimirpotekhin can you review the PR?

**Review by vladimirpotekhin — APPROVED** [review]
