### PR TITLE
fix(kit): `InputDateTime` with `[min]` / `[max]` distorts value on click

### LINKED ISSUE #7586: 🐞 - `InputDateTime` with `[max]` distorts value on click
### Playground Link

https://stackblitz.com/edit/input-date-time-max-as-current-date-time

### Description

1. Open https://stackblitz.com/edit/input-date-time-max-as-current-date-time
2. Click on the 1st textfield many times

https://github.com/taiga-family/taiga-ui/assets/35179038/3922eae8-218d-467e-986f-46953e7ec7a1

### Angular version

17

### Taiga UI version

3.61.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by nsbarsukov**
Closes #7586

### CODE REVIEW

File: projects/kit/components/input-date-time/input-date-time.component.ts [hunk 1]
```diff
@@ -450,6 +450,6 @@ export class TuiInputDateTimeComponent
             return tuiDay;
         }
 
-        return [tuiDay, tuiTime];
+        return value as [TuiDay, TuiTime];
```
Comment (nsbarsukov) [inline projects/kit/components/input-date-time/input-date-time.component.ts:453]: The same as `main`-branch:
https://github.com/taiga-family/taiga-ui/blob/daeba7b6363d9312ab87d2fc1eab16541c4ecce0/projects/legacy/components/input-date-time/input-date-time.component.ts#L441

**Review by vladimirpotekhin — APPROVED** [review]

**Review by splincode — APPROVED** [review]
