### PR TITLE
fix(core): emit tuiDropdownOpenChange on distinct values

### LINKED ISSUE #9609: 🐞 - Multi-Select - tuiDropdownOpenChange emitting two events
### Reproduction url

https://stackblitz.com/edit/angular-u8tdmj?file=src%2Fapp%2Fapp.component.html

### Description

When opening and closing the multi-select dropdown two events are being emitted from the tuiDropdownOpenChange output. Check stackblitz for example.

### Taiga UI version

3.96

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by shiv9604**
Fixes #9609

Description : 
1. We used `Subject` because we are concerned about the latest value compared to maintaining the last state.
2. Created the `emitOpenChange` method to centralize & handle responsibility for emitting values.
3. Replaced previous value emission logic with the currently integrated flow.

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/core/directives/dropdown/dropdown-open-legacy.directive.ts [hunk 1]
```diff
@@ -10,11 +10,19 @@ import {BehaviorSubject} from 'rxjs';
         '[tuiDropdownOpen]:not([tuiDropdown]),[tuiDropdownOpenChange]:not([tuiDropdown])',
 })
 export class TuiDropdownOpenLegacy {
+    private readonly openStateSub = new Subject<boolean>();
+
     @Output()
-    public readonly tuiDropdownOpenChange = new BehaviorSubject(false);
+    public readonly tuiDropdownOpenChange = this.openStateSub
+        .asObservable()
```
Comment (waterplea) [inline projects/core/directives/dropdown/dropdown-open-legacy.directive.ts:17]: Unnecessary, pipe would already turn it into Observable

**Review by waterplea — APPROVED** [review]

File: projects/core/directives/dropdown/dropdown-open-legacy.directive.ts (hunk 1 above)
Comment (shiv9604) [reply projects/core/directives/dropdown/dropdown-open-legacy.directive.ts]: Thanks for pointing that out.
Resolved!
