### PR TITLE
fix(core): set `text` input mode for iOS devices when use negative values

### LINKED ISSUE #3902: 🐞 - It is not possible to specify inputmode in tui-input
### Which @taiga-ui/* package(s) are the source of the bug?

core, kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-rtk3v8

### Is this issue blocking you?

Non-Blocking

### Description

In `tui-input`, you cannot specify input mode to display the numeric keypad, for example.

Because `tui-input-number` displays the default numeric keypad in ios, you cannot enter a negative value.

### Angular version

*

### Taiga UI version

3.20.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #3902

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/kit/components/input-number/input-number.directive.ts [hunk 1]
```diff
@@ -27,6 +27,6 @@ export class TuiInputNumberDirective
         }
 
         this.host.nativeFocusableElement.maxLength = this.host.calculatedMaxLength;
-        this.host.nativeFocusableElement.inputMode = 'decimal';
```
Comment (nsbarsukov) [inline projects/kit/components/input-number/input-number.directive.ts:30]: Does it toggle `inputMode` for all cases ?

Maybe only ?
`this.isIOS && this.isNegativeAllowed ? 'decimal' : 'text'`

Comment (nsbarsukov) [reply projects/kit/components/input-number/input-number.directive.ts:30]: https://github.com/Tinkoff/taiga-ui/blob/ca8a441f546f3c758132671e79963ff5faefb2cb/projects/kit/components/input-number/input-number.component.ts#L121-L128

Comment (splincode) [reply projects/kit/components/input-number/input-number.directive.ts:30]: right now `get inputMode` doesn't usage anywhere

Comment (splincode) [reply projects/kit/components/input-number/input-number.directive.ts:30]: after

image

Comment (nsbarsukov) [reply projects/kit/components/input-number/input-number.directive.ts:30]: it will be perfect to keep the same condition: show `text` keyboard when minus is required, otherwise show cool `decimal`-keyboard

Comment (splincode) [reply projects/kit/components/input-number/input-number.directive.ts:30]: @splincode ```this.host.nativeFocusableElement.inputMode = this.host.inputMode;```

host is `TuiInputNumberComponent` where `inputMode` getter is  https://github.com/Tinkoff/taiga-ui/blob/ca8a441f546f3c758132671e79963ff5faefb2cb/projects/kit/components/input-number/input-number.component.ts#L121-L128

File: projects/core/components/primitive-textfield/textfield/textfield.component.ts [hunk 2]
```diff
@@ -20,6 +20,7 @@ import {TUI_TEXTFIELD_HOST} from '@taiga-ui/core/tokens';
     providers: [TEXTFIELD_CONTROLLER_PROVIDER],
     host: {
         type: 'text',
+        '[attr.inputmode]': 'host.inputMode',
```
Comment (waterplea) [inline projects/core/components/primitive-textfield/textfield/textfield.component.ts:23]: We need to make sure users can override it. Look at how `id` is done.

**Review by waterplea — CHANGES_REQUESTED** [review]

File: projects/core/components/primitive-textfield/textfield/textfield.component.ts (hunk 2 above)
Comment (splincode) [reply projects/core/components/primitive-textfield/textfield/textfield.component.ts]: fixed

**Comment by splincode** [comment]
@waterplea @nsbarsukov @vladimirpotekhin Hello, please review me later :)

**Review by nsbarsukov — CHANGES_REQUESTED** [review]
```
 FAIL  projects/core/components/primitive-textfield/test/textfield.component.spec.ts
  Textfield
    id binding
      ✕ Auto id generation works (45 ms)
      ✓ Static id is not overridden (7 ms)
      ✓ Dynamic id binding works (6 ms)
  ● Textfield › id binding › Auto id generation works
    expect(received).toBeTruthy()
    Received: ""

      64 |     describe(`id binding`, () => {
      65 |         it(`Auto id generation works`, () => {
    > 66 |             expect(testComponent.auto.nativeElement.id).toBeTruthy();
         |                                                         ^
      67 |         });
```

**Comment by splincode** [comment]
@nsbarsukov sorry, about that, I thought it was e2e flaky

**Review by nsbarsukov — CHANGES_REQUESTED** [review]
:harold:

```ts
Textfield › id binding › Dynamic id binding works
    NG0100: ExpressionChangedAfterItHasBeenCheckedError:
    Expression has changed after it was checked.
    Previous value for 'inputMode': 'undefined'.
    Current value: 'undefined'..
    Find more at https://angular.io/errors/NG0100
```

**Comment by splincode** [comment]
@nsbarsukov fixed, sorry again

**Review by nsbarsukov — APPROVED** [review]

**Review by waterplea — APPROVED** [review]
