### PR TITLE
fix(kit): `ComboBox` / `InputTime` has broken cleaner

### LINKED ISSUE #11323: 🐞 - `ComboBox` / `InputTime` has broken cleaner
### Reproduction url

https://taiga-ui.dev/components/combo-box#basic
https://taiga-ui.dev/components/input-time#mode

### Description

Press cleaner icon. Value is not cleaned

Relates:
* https://github.com/taiga-family/taiga-ui/pull/11313

`update` function is executed too early (before `textfield.value.set` inside `setValue` updated DOM)
https://github.com/taiga-family/taiga-ui/blob/6dbfd964d721717b64f6366899fd08b0fd792a97/projects/cdk/utils/dom/value.ts#L43-L45
### Taiga UI version

4.45.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by nsbarsukov**
Fixes #11323

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/kit/components/combo-box/combo-box.directive.ts [hunk 1]
```diff
@@ -127,13 +130,8 @@ export class TuiComboBox<T>
...
     public setValue(value: T | null): void {
-        const stringified = this.stringify(value);
-
-        if (stringified !== this.textfield.value()) {
-            this.textfield.value.set(stringified);
-            setTimeout((end = stringified.length) => this.el.setSelectionRange(end, end));
-        }
-
+        this.defaultAccessor.setValue(value);
+        setTimeout((end = this.el.value.length) => this.el.setSelectionRange(end, end));
```
Comment (waterplea) [inline projects/kit/components/combo-box/combo-box.directive.ts]: Isn't this a default behavior when input value is programmatically updated

File: projects/kit/components/input-time/input-time.directive.ts [hunk 2]
```diff
@@ -65,6 +65,8 @@ export class TuiInputTimeDirective
     private readonly fillers = toSignal(inject(TUI_TIME_TEXTS));
     private readonly prefix = signal('');
     private readonly postfix = signal('');
+    private readonly defaultAccessor: TuiTextfieldAccessor<TuiTime | null> =
```
Comment (waterplea) [inline projects/kit/components/input-time/input-time.directive.ts]: We already have `private readonly textfield = inject(TuiTextfieldDirective);`

File: projects/kit/components/input-time/input-time.directive.ts [hunk 3]
```diff
@@ -120,7 +122,12 @@ export class TuiInputTimeDirective
 
     public setValue(value: TuiTime | null): void {
         this.onChange(value);
-        this.textfield.value.set(this.stringify(value));
+
+        if (value) {
+            this.textfield.value.set(this.stringify(value));
+        } else {
+            this.defaultAccessor.setValue(value);
```
Comment (waterplea) [inline projects/kit/components/input-time/input-time.directive.ts]: What if we instead update the stringify method on tui-textfield? Then we wouldn't need branching here?

File: projects/kit/components/combo-box/combo-box.directive.ts [hunk 4]
```diff
@@ -60,6 +60,9 @@ export class TuiComboBox<T>
     private readonly itemsHandlers: TuiItemsHandlers<T | string> =
         inject(TUI_ITEMS_HANDLERS);
 
+    private readonly defaultAccessor: TuiTextfieldAccessor<T> =
```
Comment (waterplea) [inline projects/kit/components/combo-box/combo-box.directive.ts]: We already have `private readonly textfield: TuiTextfieldDirective<T> = inject(TuiTextfieldDirective);`

File: projects/kit/components/input-time/input-time.directive.ts (hunk 3 above)
Comment (nsbarsukov) [reply projects/kit/components/input-time/input-time.directive.ts]: We have the such case (see providers of the component)
https://taiga-ui.dev/components/input-time#dropdown-datalist

Should we remove `stringify` from the example and always set `stringify` internally ? 🤔

**Review by waterplea — APPROVED** [review]

File: projects/kit/components/input-time/input-time.directive.ts (hunk 3 above)
Comment (nsbarsukov) [reply projects/kit/components/input-time/input-time.directive.ts]: Discussed with @waterplea personally.
We decided not to overwrite `stringify` inside `TuiInputTimeDirective` because prefix/postfix can be not required for datalist
