### PR TITLE
fix(schematics): missed import `TuiIcon` during migration of `tuiTextfieldCustomContent`

### LINKED ISSUE #13910: 🐞 - Missed import `TuiIcon` during migration of `tuiTextfieldCustomContent`
### Reproduction url

https://github.com/taiga-family/maskito/blob/main/projects/demo/src/pages/recipes/placeholder/examples/3-date/component.ts

### Description

```ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {MaskitoDirective} from '@maskito/angular';
import {TuiInputModule, TuiTextfieldControllerModule} from '@taiga-ui/legacy';

import mask from './mask';

@Component({
    selector: 'placeholder-doc-example-3',
    imports: [
        FormsModule,
        MaskitoDirective,
        TuiInputModule,
        TuiTextfieldControllerModule,
    ],
    template: `
        <tui-input
            tuiTextfieldCustomContent="@tui.calendar"
            [style.max-width.rem]="20"
            [(ngModel)]="value"
        >
            Enter date
            <input
                inputmode="numeric"
                tuiTextfieldLegacy
                [maskito]="maskitoOptions"
            />
        </tui-input>
    `,
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PlaceholderDocExample3 {
    protected readonly maskitoOptions = mask;
    protected value = '';
}
```

are migrated to 
```ts
import { TuiInput } from "@taiga-ui/core";
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {MaskitoDirective} from '@maskito/angular';
import mask from './mask';

@Component({
    selector: 'placeholder-doc-example-3',
    imports: [
        FormsModule,
        MaskitoDirective,
        TuiInput
    ],
    template: `
        <!-- TODO: (Taiga UI migration) tui-input migration (see https://taiga-ui.dev/components/input):
     - "[style" is an unrecognized attribute and was placed on <tui-textfield>. Move it to <input tuiInput> if it targets the native element.
-->
        <tui-textfield [style.max-width.rem]="20">
        <input
                inputmode="numeric"
                tuiInput
                [maskito]="maskitoOptions" [(ngModel)]="value"/>

        <tui-icon icon="@tui.calendar" />
        </tui-textfield>
    `,
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PlaceholderDocExample3 {
    protected readonly maskitoOptions = mask;
    protected value = '';
}
```

It throws
```
✘ [ERROR] NG8001: 'tui-icon' is not a known element:
1. If 'tui-icon' is an Angular component, then verify that it is included in the '@Component.imports' of this component.
2. If 'tui-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@Component.schemas' of this component to suppress this message. [plugin angular-compiler]

    projects/demo/src/pages/recipes/placeholder/examples/3-date/component.ts:24:8:
      24 │         <tui-icon icon="@tui.calendar" />
         ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

We should also add `TuiIcon` import!
Don't use `tui-textfield[iconEnd]` because it can be already occupied by `[tuiChevron]`!

### Taiga UI version

5.3.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by nsbarsukov**
Fixes #13910

### CODE REVIEW

File: projects/cdk/schematics/utils/add-import-to-closest-module.ts [hunk 1]
```diff
@@ -84,3 +85,26 @@ export function saveAddedImports(options: TuiSchema): void {
 
     importsToAdd.clear();
 }
+
+// TODO: use `isStandaloneComponent` from 'ng-morph@5.0.0'
+function isStandaloneComponent(component: ClassDeclaration): boolean {
```
Comment (nsbarsukov) [inline projects/cdk/schematics/utils/add-import-to-closest-module.ts]: Don't merge until ng-morph is bumped and utility is deleted

**Review by splincode — APPROVED** [review]
