### PR TITLE
fix(cdk): `TuiDay` incorrectly appends month in backward direction

### LINKED ISSUE #11409: 🐞 - `CalendarRange` with `[minLength]="{month: 1}"` has incorrect limits for backward direction
### Reproduction url

https://stackblitz.com/edit/tui-calendar-range-min-length-m1?file=src%2Fapp%2Fapp.component.ts

### Description

Image

<br />

01.03.2018 can be selected as the end of range

**Expected behavior**
28.02.2018 (???)

Relates:
- https://github.com/taiga-family/maskito/pull/2210#discussion_r2224823234

### Taiga UI version

4.46.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by LarisaGl**
Fixes #11409

### CODE REVIEW

File: projects/cdk/date-time/day.ts [hunk 1]
```diff
@@ -302,11 +302,21 @@ export class TuiDay extends TuiMonth {
...
+        const currentMonthDaysCount = TuiMonth.getMonthDaysCount(
+            this.month,
+            TuiYear.isLeapYear(years),
+        );
         let days =
-            Math.min(
-                this.day,
-                TuiMonth.getMonthDaysCount(months, TuiYear.isLeapYear(years)),
-            ) + day;
+            (this.day > monthDaysCount
```
Comment (splincode) [inline projects/cdk/date-time/day.ts]: @LarisaGl lint error

File: projects/cdk/date-time/test/day.spec.ts [hunk 2]
```diff
@@ -825,17 +825,97 @@ describe('TuiDay', () => {
...
+
+                        expect(result.year).toBe(2018);
+                        expect(result.month).toBe(1);
+                        expect(result.day).toBe(28);
+                    },
+                );
+
+                it(
+                    'TuiDay {year: 2018, month: 1, day: 28} if {month: -1} was passed (when current month has' +
+                        'more days, then final month, but bought has the day)',
```
Comment (nsbarsukov) [inline projects/cdk/date-time/test/day.spec.ts]:
```suggestion
                        'more days, then final month, but both has the day)',
```

File: projects/cdk/date-time/test/day.spec.ts [hunk 3]
```diff
@@ -825,17 +825,97 @@ describe('TuiDay', () => {
...
+                    () => {
+                        const result = new TuiDay(2018, 2, 31).append({
+                            month: -1,
+                        });
+
+                        expect(result.year).toBe(2018);
+                        expect(result.month).toBe(1);
+                        expect(result.day).toBe(28);
+                    },
+                );
```
Comment (nsbarsukov) [inline projects/cdk/date-time/test/day.spec.ts:864]: Let's also provide PW tests for `CalendarRange` (to ensure that `TuiDay` is properly used inside `CalendarRange`):

1. Expand API page with new options `{month: 1}`
https://github.com/taiga-family/taiga-ui/blob/11934ca498cb92146279507a2286056e75fb2e88/projects/demo/src/modules/components/calendar-range/index.ts#L70

2. Add the following tests inside `projects/demo-playwright/tests/kit/calendar-range/calendar-range.pw.spec.ts`:

```ts
describe('[minLength] property', () => {
    let alert!: Locator;

    describe('{month: 1}', () => {
        beforeEach(async ({page}) => {
            await tuiGoto(page, `${DemoRoute.CalendarRange}/API?minLength$=2`, {
                date: new Date(2018, 1, 28),
            });
            alert = page.locator('tui-alerts tui-notification');
        });

        test('31.03.2018 => {month: 1} => 01.03.2018 // all days of March, a full month', async () => {
            const [, endSheet] = await calendarRange
                .getCalendars()
                .then(async ([x]) => x.getCalendarSheets());

            await endSheet!.clickOnDay(31);

            await expect(example).toHaveScreenshot(
                '11-1-min-length-month-1-full-march.png',
            );

            await endSheet!.clickOnDay(2);
            await expect(alert).not.toBeAttached();

            await endSheet!.clickOnDay(1);
            await expect(alert).toContainText('01.03.2018 – 31.03.2018');
        });

        // TODO:
        // - 31.03.2018 => {month: -1, day: -1} => 28.02.2018
        // - 17.03.2018 => {month: -1, day: -1} => 17.03.2018
        // - 17.03.2018 => {month: -1} => 18.02.2018
    });
});
```

Comment (nsbarsukov) [reply projects/cdk/date-time/test/day.spec.ts:864]: 11-1-min-length-month-1-full-march

Comment (nsbarsukov) [reply projects/cdk/date-time/test/day.spec.ts:864]: Add `30.03.2018 => {month: 1} => 28.02.2018` (original bug reported case from [issue](https://github.com/taiga-family/taiga-ui/issues/11409))

File: projects/cdk/date-time/day.ts (hunk 1 above)
Comment (LarisaGl) [reply projects/cdk/date-time/day.ts]: thanks! fixed

File: projects/cdk/date-time/test/day.spec.ts (hunk 2 above)
Comment (LarisaGl) [reply projects/cdk/date-time/test/day.spec.ts]: oh, sure, sorry for typo) fixed

File: projects/cdk/date-time/test/day.spec.ts (hunk 3 above)
Comment (LarisaGl) [reply projects/cdk/date-time/test/day.spec.ts:864]: sure) thanks! added

**Review by nsbarsukov — APPROVED** [review]

**Review by vladimirpotekhin — APPROVED** [review]

**Comment by splincode** [comment]
@LarisaGl Don't forget to add the cherry-pick to the v4.x branch.
