### PR TITLE
fix(kit): debounce `overflownChange` event

### LINKED ISSUE #10035: 🐞 - [LineClamp] multiple overflownChange event
### Reproduction url

-

### Description

1. open page https://taiga-ui.dev/components/line-clamp/API and set [linesLimit]=5
2. open tab "Examples"
3. open tab "API"

on init overflownChange emits true and false

Image

### Taiga UI version

4.18.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by splincode**
Fixes #10035

### CODE REVIEW

File: projects/kit/components/line-clamp/line-clamp.component.ts [hunk 1]
```diff
@@ -45,6 +49,7 @@ import {TuiLineClampPositionDirective} from './line-clamp-position.directive';
     styleUrls: ['./line-clamp.style.less'],
     changeDetection: ChangeDetectionStrategy.OnPush,
     providers: [
+        ResizeObserverService,
```
Comment (waterplea) [inline projects/kit/components/line-clamp/line-clamp.component.ts:52]: Not used?

**Review by waterplea — APPROVED** [review]

**Review by mdlufy — APPROVED** [review]

File: projects/demo/src/modules/components/line-clamp/examples/3/index.ts [hunk 2]
```diff
@@ -1,19 +1,23 @@
...
-    imports: [TuiLineClamp],
+    imports: [TuiLineClamp, WaResizeObserver],
     templateUrl: './index.html',
     styleUrls: ['./index.less'],
     encapsulation,
     changeDetection,
 })
 export default class Example {
     private readonly win = inject(WA_WINDOW);
+    private readonly cd = inject(ChangeDetectorRef);
```
Comment (mdlufy) [inline projects/demo/src/modules/components/line-clamp/examples/3/index.ts:18]: maybe `cd` => `cdr` for consistency?

Comment (splincode) [reply projects/demo/src/modules/components/line-clamp/examples/3/index.ts]: fixed
