### PR TITLE
fix(core): prevent dropdown focus break with conditional @if/@else inputs

### LINKED ISSUE #13445: 🐞 - TuiTextfield: dropdown focus breaks when inputs inside the `TextField` are wrapped in @if/@else
### Reproduction url

https://stackblitz.com/edit/angular-rj9zxlhj?file=src%2Fapp%2Fmulti-select-input%2Fmulti-select-input.ts

### Description

`textfield` contains two inputs wrapped in `@if/@else`. If both fields are present in the same container (toggled with `@if`), the dropdown behavior breaks. If only one input is present, everything works correctly.

**Expected:**
Dropdown behavior should work the same with conditional input rendering.

**Actual:**
Dropdown behavior breaks when using conditional rendering for two inputs.

**Possible cause:**
Some `contentChild` queries in the `textfield` require `{ descendants: true }` for this case.

### Taiga UI version

4.72.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by nullawhale**
Fixes #13445

### CODE REVIEW

File: projects/core/components/textfield/textfield.component.ts [hunk 1]
```diff
@@ -79,7 +79,10 @@ export class TuiTextfieldBaseComponent<T>
     protected readonly auxiliaryQuery: QueryList<object> = EMPTY_QUERY;
 
     // TODO: Added just to avoid breaking anything until we refactor to signal queries
-    @ContentChild(forwardRef(() => TuiTextfieldBase), {read: ElementRef})
+    @ContentChild(forwardRef(() => TuiTextfieldBase), {
```
Comment (splincode) [inline projects/core/components/textfield/textfield.component.ts:82]: Hello, could you add a unit test or an e2e test (Cypress or Playwright) to prevent this issue in the future?

File: projects/core/components/textfield/textfield.component.ts [hunk 2]
```diff
@@ -109,16 +112,16 @@ export class TuiTextfieldBaseComponent<T>
...
     public readonly control?: NgControl;
 
-    @ContentChild(TuiControl)
+    @ContentChild(TuiControl, {descendants: true})
     public readonly cva?: TuiControl<unknown>;
 
     // TODO: Replace with signal query when Angular is updated v5
     @ContentChild(forwardRef(() => TuiTextfieldBase), {
         read: ElementRef,
-        static: true,
```
Comment (waterplea) [inline projects/core/components/textfield/textfield.component.ts:121]: I have a feeling this was here for a reason 🤔

Comment (nullawhale) [reply projects/core/components/textfield/textfield.component.ts:121]: I couldn’t find a clear reason for using static, but it directly affected to search for input inside the @if wrapper

File: projects/core/components/textfield/textfield.component.ts (hunk 1 above)
Comment (nullawhale) [reply projects/core/components/textfield/textfield.component.ts:82]: Could you please tell me what the error might be in "E2E testing / E2E result (pull_request)"?
Locally test passes successful, but here it fails for some unclear reason

File: projects/core/components/textfield/textfield.component.ts (hunk 2 above)
Comment (waterplea) [reply projects/core/components/textfield/textfield.component.ts:121]: Without it there will be ExpressionChange error in v4. In main there's already a signal so that's ok, but here we probably need to add another non-static prop for the same thing to use it when focusing so that it fixes your issue and keeps the change detection working as expected:
https://github.com/taiga-family/taiga-ui/pull/8809

Comment (nullawhale) [reply projects/core/components/textfield/textfield.component.ts:121]: I restored `static: true` for the `input` and used `_input` with `descendants: true` for focus logic

File: projects/demo/src/modules/components/input-chip/examples/4/index.html [hunk 3]
```diff
@@ -69,6 +69,50 @@
     </tui-textfield>
 </label>
 
+<div
+    *ngIf="isE2E"
```
Comment (waterplea) [inline projects/demo/src/modules/components/input-chip/examples/4/index.html]: We shouldn't add examples just for tests. It's ok to show it on demo as an example of conditionally switching between editable and select-like behavior.

Comment (nullawhale) [reply projects/demo/src/modules/components/input-chip/examples/4/index.html]: Made the example more beautiful and removed the check

File: projects/demo/src/modules/components/input-chip/examples/4/index.html [hunk 4]
```diff
@@ -69,6 +69,46 @@
     </tui-textfield>
 </label>
 
+<div>
```
Comment (waterplea) [inline projects/demo/src/modules/components/input-chip/examples/4/index.html]: nitpicking: unnecessary `div`?

File: projects/demo/src/modules/components/input-chip/examples/4/index.less [hunk 5]
```diff
@@ -4,3 +4,9 @@
     flex-direction: column;
     gap: 1rem;
 }
+
+.conditional-input-row {
```
Comment (waterplea) [inline projects/demo/src/modules/components/input-chip/examples/4/index.less]: Is this used somewhere?

File: projects/demo/src/modules/components/input-chip/examples/4/index.html (hunk 4 above)
Comment (nullawhale) [reply projects/demo/src/modules/components/input-chip/examples/4/index.html]: It was a visual wrapper. Removed

File: projects/demo/src/modules/components/input-chip/examples/4/index.less (hunk 5 above)
Comment (nullawhale) [reply projects/demo/src/modules/components/input-chip/examples/4/index.less]: Nowhere. Forgot to remove

**Comment by nullawhale** [comment]
Looks like I ruined the branch with a rebase. Should I create a new branch? And should I squash all my commits?

**Comment by waterplea** [comment]
@nullawhale up to you, commits are squashed when merged anyway, so whatever is easier for you

**Comment by splincode** [comment]
@nullawhale Hello, could you add cherry pick to main, please
