### PR TITLE
fix(cdk): watch font size only on root

### LINKED ISSUE #13300: 🗂 - A lot of iframes on demo
### Description

Image

### PR DESCRIPTION
**Pull request by splincode**
Fixes #13300

### CODE REVIEW

File: projects/cdk/directives/font-size/font-size.directive.ts [hunk 1]
```diff
@@ -3,18 +3,24 @@ import {DestroyRef, Directive, inject, InjectionToken, PLATFORM_ID} from '@angul
...
 @Directive()
 export class TuiFontSize {
+    private readonly iframe = inject(CACHED_IFRAME);
     private readonly handler = inject(TUI_FONT_SIZE_HANDLER, {optional: true});
     protected readonly nothing = inject(DestroyRef).onDestroy(
         this.handler &&
             isPlatformBrowser(inject(PLATFORM_ID)) &&
             typeof ResizeObserver !== 'undefined'
-            ? tuiFontSizeWatcher(this.handler, inject(DOCUMENT).createElement('iframe'))
+            ? tuiFontSizeWatcher(this.handler, this.iframe)
```
Comment (waterplea) [inline projects/cdk/directives/font-size/font-size.directive.ts]: You can inject it directly in here, without storing on "this."

Comment (splincode) [reply projects/cdk/directives/font-size/font-size.directive.ts]: fixed
