### PR TITLE
fix(kit): `inputChip` - add special character clearing

### LINKED ISSUE #12427: 🐞 - `InputChip` - When pasting text, special characters are not removed.
### Reproduction url

https://stackblitz.com/edit/angular-ttpdkske?file=src%2Fapp%2Fapp.template.html

### Description

Hi! When pasting comma-separated text, for example, from Notepad, special characters like `\r\n` remain. They are not visible visually, but can easily cause a lot of problems when further working with the value.

### Taiga UI version

4.60.0

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by Stivin**
Added clearing of special characters when pasting and dropping text.

Fixes #12427

### CODE REVIEW

**Review by waterplea — APPROVED** [review]

File: projects/kit/components/input-chip/input-chip.directive.ts [hunk 1]
```diff
@@ -112,7 +112,10 @@ export class TuiInputChipBaseDirective<T>
                 ? event.dataTransfer?.getData('text/plain') || ''
                 : tuiGetClipboardDataText(event);
 
-        this.textfield.value.set(value);
+        // eslint-disable-next-line no-control-regex
+        const cleanedValue = value.replaceAll(/[\x00-\x1F\x7F-\x9F]/g, '');
```
Comment (splincode) [inline projects/kit/components/input-chip/input-chip.directive.ts]: @nsbarsukov Is it worth making some kind of service with `fromControlValue/toControlValue` for textfields?

Comment (waterplea) [reply projects/kit/components/input-chip/input-chip.directive.ts]: This text is cleaned before it actually goes to control so I don't think so

Comment (splincode) [reply projects/kit/components/input-chip/input-chip.directive.ts]: Maybe, we can add to utils:

```ts
/**
 * Sanitizes pasted or dropped text by removing invisible and control characters
 * that can appear in clipboard or drag-and-drop data.
 *
 * Removes:
 * 1. ASCII control characters (0x00–0x1F) — non-printable characters like
 *    NULL, BEL, BS, CR, LF, TAB, ESC, etc.
 * 2. Extended control characters (0x7F–0x9F) — C1 control codes from ISO-8859-1,
 *    often found in legacy or malformed text encodings.
 * 3. Zero-width and special Unicode characters:
 *    - U+200B ZERO WIDTH SPACE
 *    - U+200C ZERO WIDTH NON-JOINER
 *    - U+200D ZERO WIDTH JOINER
 *    - U+FEFF BYTE ORDER MARK (BOM)
 *
 * @param {string} value - The input string from clipboard or drag event.
 * @returns {string} - A cleaned string without control or invisible characters.
 *
 * @example
 * tuiSanitizeText('Hello\u0000World\u200B!');
 * // → "HelloWorld!"
 */
export function tuiSanitizeText(value: string): string {
    return value
        .replaceAll(/[\x00-\x1F\x7F-\x9F]/g, '')
        .replaceAll(/[\u200B-\u200D\uFEFF]/g, '');
}
```

and then just:

```ts
this.textfield.value.set(tuiSanitizeText(value));
```

Comment (Stivin) [reply projects/kit/components/input-chip/input-chip.directive.ts]: @splincode Do you want to see this in the CDK miscellaneous or the core miscellaneous?

Comment (splincode) [reply projects/kit/components/input-chip/input-chip.directive.ts]: `CDK miscellaneous`

**Review by splincode — APPROVED** [review]

**Comment by vladimirpotekhin** [comment]
@Stivin can you resolve conflicts plz?

**Comment by Stivin** [comment]
> @Stivin can you resolve conflicts plz?

merge conflict fixed

**Comment by splincode** [comment]
@waterplea fyi

**Comment by splincode** [comment]
@Stivin don't forget add cherry pick to v4.x, please
