### PR TITLE
fix(experimental): `PdfPreview` use `isMobileRes` token for header

### LINKED ISSUE #12276: 🐞 - pdfViewer in mobile resolution has extra header
### Reproduction url

https://taiga-ui.dev/components/pdf-viewer

### Description

pdfViewer in mobile resolution has extra header  https://taiga-ui.dev/components/pdf-viewer

### Taiga UI version

4.х

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
Fixes #12276

### CODE REVIEW

File: projects/experimental/components/pdf-viewer/pdf-viewer.component.ts [hunk 1]
```diff
@@ -31,11 +34,18 @@ import {injectContext} from '@taiga-ui/polymorpheus';
...
-        '[attr.tuiTheme]': 'isMobile ? "" : "dark"',
+        '[attr.tuiTheme]': 'isMobileRes() ? "" : "dark"',
     },
 })
 export class TuiPdfViewerComponent<O, I> {
-    protected readonly isMobile = inject(TUI_IS_MOBILE);
+    protected readonly isMobileRes = toSignal(
+        inject(TuiBreakpointService).pipe(
+            map((breakpoint) => breakpoint === 'mobile'),
+            tuiWatch(),
```
Comment (waterplea) [inline projects/experimental/components/pdf-viewer/pdf-viewer.component.ts]: Do we need tuiWatch here?

**Review by waterplea — APPROVED** [review]
