### PR TITLE
fix(kit): navigate to active element after first render for `tuiStepper`

### LINKED ISSUE #10737: 🐞 - `Stepper` error setting initial index
### Reproduction url

https://stackblitz.com/edit/angular-gih7qray

### Description

Initial setting of the `activeItemIndex` doesn't work, starts working if set with a delay

### Taiga UI version

4

### Browser Used

Chrome

### OS Used

macOS

### PR DESCRIPTION
**Pull request by splincode**
Fixes #10737

### CODE REVIEW

File: projects/kit/components/stepper/stepper.component.ts [hunk 1]
```diff
@@ -72,12 +73,20 @@ export class TuiStepperComponent {
 
     @Input('activeItemIndex')
     public set activeIndex(index: number) {
+        this.itemIndex = index;
+
         if (this.steps.get(index)?.nativeElement) {
             this.activeItemIndex = index;
```
Comment (waterplea) [inline projects/kit/components/stepper/stepper.component.ts:79]: Why do we only update internal index if there is such a step? That would cause out of sync situations when external index is A and internally we have B. Shouldn't we update it all the time and scroll to the element only when it's there?

Also what if we change from setter to `ngOnChanges`? Would content children be processed by then?

Comment (splincode) [reply projects/kit/components/stepper/stepper.component.ts]: fixed

File: projects/kit/components/stepper/stepper.component.ts [hunk 2]
```diff
@@ -58,24 +58,21 @@ export class TuiStepperComponent {
     private readonly speed = inject(TUI_ANIMATIONS_SPEED);
     private readonly destroyRef = inject(DestroyRef);
 
-    protected activeItemIndex = 0;
-
     protected readonly $ = inject(ResizeObserverService, {self: true})
         .pipe(takeUntilDestroyed())
         .subscribe(() => this.scrollIntoView(this.activeItemIndex));
 
+    @Input('activeItemIndex')
```
Comment (waterplea) [inline projects/kit/components/stepper/stepper.component.ts:65]: Unnecessary alias

**Review by waterplea — APPROVED** [review]

File: projects/kit/components/stepper/stepper.component.ts (hunk 2 above)
Comment (splincode) [reply projects/kit/components/stepper/stepper.component.ts]: fixed

**Review by vladimirpotekhin — APPROVED** [review]
