### PR TITLE
fix(core): `DropdownHover` fix unexpected closing when using nested dropdown

### LINKED ISSUE #5395: 🐞 - `tuiDropdownHover`: closes after canceling the selection in `tui-select`
### Playground Link

https://stackblitz.com/edit/angular-fwx3yj-hhg8tt?file=src%2Fapp%2Fapp.component.html

### Description

This bug is related to #4056

https://github.com/taiga-family/taiga-ui/assets/2184564/f3fa9a16-7df5-4935-99b8-b2af2340d21e

### Angular version

16.2.5

### Taiga UI version

3.44.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #5395

### CODE REVIEW

File: projects/core/directives/dropdown/dropdown-hover.directive.ts [hunk 1]
```diff
@@ -39,11 +39,19 @@ export class TuiDropdownHoverDirective extends TuiDriver {
...
+        @Inject(TuiDropdownHoverDirective)
+        private readonly parentHover: TuiDropdownHoverDirective | null,
     ) {
         super(subscriber => this.stream$.subscribe(subscriber));
     }
 
     toggle(visible: boolean): void {
+        if (this.parentHover) {
+            this.parentHover.toggle(visible);
+        }
```
Comment (splincode) [inline projects/core/directives/dropdown/dropdown-hover.directive.ts:53]: `this.parentHover?.toggle(visible);`

**Review by splincode — APPROVED** [review]

**Review by waterplea — APPROVED** [review]
